### ISSUE TITLE
Not possible to save a new page as a shadow page

### ISSUE THREAD

**Issue by sRmarcos** [sulu/sulu#1381]
When you create a page and without saving it you set the shadow page feature you get an error when you try to save it. When you first save the page and you later set the shadow page it works.

@danrot guest that it is because the new page does not have a title jet.

**Comment by wachterjohannes** [comment]
i have discussed this with @chirimoya and we think there should be a url and a title field for a shadow page ... /cc @berndhep

**Comment by berndhep** [comment]
Features that require a title and URL should only appear once the page has been saved for the first time.

**Comment by danrot** [comment]
@berndhep The problem here is that the URL and title already have to be saved in the correct language. So if you have a page in english, you would have to save it in german with a title first, before you can create a german shadow page. IMO the feature would be quite hidden then.

**Comment by berndhep** [comment]
I see. Then the case is like @wachterjohannes has described it. E.g.: When you save the page the english title has to be set for the german shadow page. But you can edit this in the URL and title field of the german page.

**Comment by wachterjohannes** [comment]
@berndhep thats what i thought :+1:

**Comment by danrot** [comment]
Have had some troubles while creating https://github.com/sulu-io/sulu/pull/1795, it looks like it is currently not possible to create a shadow page immediately, even when working with the `ContentMapper` directly (that's why I've had to save the page twice in the test: https://github.com/sulu-io/sulu/pull/1795/files#diff-ce30b59018d9b2caee2667e786543184R2990).

I've encountered two problems here:
* The check at https://github.com/sulu-io/sulu/blob/e6496d452d12c681e8c53fdb63b9e464b37cec58/src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php#L103 doesn't work as expected, because it contains a type safe check, and the `getRedirectType`-method returns a string instead of an int when ran over a HTTP request (so I am not sure this lines are doing what is intended)
* When the shadow page for `en` is created in one step, the values of the resource segment of the document and the url field of the structure differ, so that the english page receives the german URL value.

Just putting it here, so that we remember once we implement that feature.

**Comment by niklasnatter** [comment]
Since version 2.0, it is not possible to create a new page as shadow page in a single step through the UI (I also think this does not make sense because a shadow page needs a target locale that is a normal page). 

Adding a new localization as shadow page did not cause any problems for me. Therefore I am going to close this 🙂
