### ISSUE TITLE
Support insertion of custom routes into sitemap.xml

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#1403]
I have custom routes which I want to be indexed in the sitemap xml.

It would be awesome to just create tag a service with a specific Interface.

We should also include an SitemapItem class which the CR Pages also used. So the sitemap twig template will have no problems. 

e.g.

``` php
interface SitemapExtension
{
    /**
     * @return SitemapItem[]
     */
     public function getSites(
          $domain, // needed for #991
          $webpace = null,
          $portal = null,
          $localizations = array()
     );
}
```

the service should just need to be tagged:

``` xml
<tag name="sulu.sitemap.extension" />
```

**Comment by danrot** [comment]
If this is really a requirement I would not call it a `SitemapExtension`, but a `SitemapProvider`. Then the class which is currently providing these routes would also be an implementation of the `SitemapProviderInterface`, and they could be handled the same way. Then all of these classes could be handled in a simple loop, and no additional logic is required.

**Comment by alexander-schranz** [comment]
sounds good will implement this soon. is `SitemapItem` good name for one sitemap entry item?
this class will have the following properties: `loc`, 'lastmod`, `alternates` one alternate should also be a class(`SitemapItemAlternative?`) with `hreflang` and `href`

**Comment by danrot** [comment]
Not sure about the naming... Usually we don't use abbreviations, and I would slightly prefer to keep it this way (maybe the items are used in something different than an xml sitemap in the future, that's why I would not couple too tight to these names).

`SitemapItem` sounds good to me, but if I would decide on the property names I would call them `location`, `lastModified` and so on. And maybe we'll find a way to use the same class for the alternate?
