### ISSUE TITLE
Checkbox group content type

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#1741]
implement a content type which has multiple checkboxes or radios. the values should be configurable over the params or a service (for 3rd-party webservices or xml loading).

**Comment by wachterjohannes** [comment]
@berndhep can you add a screenshot of a design?

**Comment by berndhep** [comment]
![bildschirmfoto 2015-11-03 um 08 20 31](https://cloud.githubusercontent.com/assets/7425459/10902896/c22c9dca-8203-11e5-8164-c6e4fd944d10.png)

**Comment by alexander-schranz** [comment]
maybe from the configuration we can use it the same way as the symfony choice form type with expanded and multiple? http://symfony.com/doc/current/reference/forms/types/choice.html#select-tag-checkboxes-or-radio-buttons what you think @wachterjohannes?

**Comment by danrot** [comment]
Related to #424

**Comment by danrot** [comment]
Almost solved completely, but still missing the toggler with a grouping function (the toggler can only be used on its own, but not as a group in the MultipleSelect content type)

**Comment by danrot** [comment]
I had a look at this issue (the one with the toggler), and realized it is not that easy to solve, because of [this line](https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js#L234).

There is a circular reference. The toggler is an aura component which creates a hidden checkbox, which is usually fetched by the husky-validation library. The husky-validation library gathers all form elements when the `createForm` method is called. But the `sandbox.start` method is called after the form has been set, which is necessary because `createForm` sets the data on the elements. Now `createForm` is called before the togglers have been created, and therefore there is also no checkbox to find.

A solution might be a separate component containing multiple togglers.
