### ISSUE TITLE
Check for unique url should include check for existing reference to page

### ISSUE THREAD

**Issue by c00n84** [sulu/sulu#1993]
If you create a shadow page non existing parent pages already cause a url to be in the routing tree.

https://github.com/sulu-io/sulu/blob/5f9980946a89deda0ff54de8f539d7d64fcaf065/src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php#L616

**Comment by danrot** [comment]
Also the existing url should cause a `ResourceLocatorAlreadyExistsException` instead of a `ResourceLocatorNotValidException`. Then we could also remove the try/catch block around the `NodeController::postAction`.

**Comment by danrot** [comment]
Seems now also to be related to #1776. If we create a shadow page it behaves as it has been described there (meaning it does not generate this empty node as it was described here). So it would not be necessary to change this check, but implement the suggested behavior in #1776 correctly.

**Comment by danrot** [comment]
Closing this issue, because we decided the handling should be the same as in #1776. Also the current state doesn't produce route nodes without `sulu:content` properties and it shouldn't do that anyway. So the change suggested in this issue shouldn't be applied anyway, if these circumstances occur it is a bug.
