### ISSUE TITLE
Internal-link: if the webspace doesn't exist in the requested locale it shouldn't be visible

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#2026]
If you have 2 webspaces with different locales the internal link cannot open the column-select overlay because it cannot find the locale for the second webspace. Bug is in this class https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Component/Content/Compat/LocalizationFinder.php#L42 .

if we dont want to disable the webspace we could also return here "any" locale and then let the user select the locale in the internal-link content-type

**Comment by webmozart** [comment]
In general, issue tickets should be short and descriptive, while issue descriptions should be elaborate enough to describe to the reader what the problem is and how it can be reproduced. I understand this can be tedious, but it's the only way to open up internal development processes to outside people. Additionally, well described issues can be analyzed much easier in retrospective when you need to read and understand them again several years  later.

**Comment by wachterjohannes** [comment]
@webmozart i have added a few more information about the bug

**Comment by webmozart** [comment]
@wachterjohannes thanks :)

**Comment by chirimoya** [comment]
@wachterjohannes do we need a hotfix for this issue? Else remove the `Critical` label.

**Comment by wachterjohannes** [comment]
currently its enough to adding the locales to both webspaces (you can reduce the number of locales published in the portal anyway) so for 1.1 its not so critical maybe try to include it into 1.2? /cc @danrot  @chirimoya should we add the milestone?

**Comment by danrot** [comment]
That's not the cleanest solution, but it would work, so I would say we can fix that for 1.2, if possible.
