### ISSUE TITLE
Preview errors on embedded esi with requestanalyzer service

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2041]
When a service which is used in an esi use the requestanalyzer the preview return an error.
On the website it works fine.

![requestanalyzererror](https://cloud.githubusercontent.com/assets/1698337/13300735/d686628c-db41-11e5-98a7-35c9a1db6770.png)

Easiest way to reproduce the bug create an esi controller action with the services and call it in a twig template

```php
public function embedAction() {
        $requestAnalyzer = $this->get('sulu_core.webspace.request_analyzer');
        $this->get('sulu_website.resolver.request_analyzer')->resolve($requestAnalyzer);

       return new Response('ESI');
}
```

```twig
{{ render_esi(controller('ClientWebsiteBundle:Test:embed')) }}
```

Sulu v1.1

**Comment by wachterjohannes** [comment]
hmm i think this happens because the preview is not rendered in the website kernel .... therefor the context is admin and another request-analyzer class is used. This class https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Component/Webspace/Analyzer/AdminRequestAnalyzer.php returns often null for values maybe we could give it a try to render the preview in the website kernel.
