### ISSUE TITLE
Snippet can’t be deleted because it is still referenced after a template change

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2052]
A snippet can’t be deleted if it is referenced on a page. This leads to snippets which can’t be deleted as they are still referenced in PHPCR but are not visible in the admin area after a template change (this is because changing the template does not delete the data of the "old" template - see #46).

EDIT: Just saw that the snippet can be deleted anyway but the listed references are confusing.

**Comment by danrot** [comment]
It might also be possible to solve this using `WEAKREFERENCE` instead of `REFERENCE` for these properties. But I have to check that first.

**Comment by danrot** [comment]
I have tested this issue again, and saw that you get the correct overlay when trying to delete the snippet, even if the page referencing it has changed its template:

![image](https://cloud.githubusercontent.com/assets/405874/17428080/ed0cef66-5ae5-11e6-83dd-582c1918d685.png)

But if you click that you want to delete the snippet in this overlay the request still fails, because the changes are not correctly transferred to the published namespace. I've created a separate issue for that: https://github.com/sulu/sulu/issues/2752
