### ISSUE TITLE
Invalid routing key?

### ISSUE THREAD

**Issue by sagikazarmark** [sulu/sulu#2145]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | develop

#### Actual Behavior

Cache clearing fails with the message: `The routing file "/var/www/vendor/sulu/sulu/src/Sulu/Bundle/CategoryBundle/Resources/config/routing_api.yml" contains unsupported keys for "sulu_category.keywords": "parent". Expected one of: "r  
  esource", "type", "prefix", "pattern", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition".`

Introduced in: https://github.com/sulu-io/sulu/commit/aef3f921b7846b6c82bdaae4636215d897740b6e#diff-6ce626275274b94b2468ebc3d02f8442R7

**Comment by sagikazarmark** [comment]
Sorry, my bad. I missed this: https://github.com/sulu-io/sulu-standard/commit/c4ae67933762cb8ce00673ff40fe1d1dc3b52ee7#diff-a8168136cb72fe0b04deb2dd77277df7R57

I wonder if these routes could be simplified somehow, because it is not obvious that updating the core requires updating the application as well (even if it is dev branch).

**Comment by chirimoya** [comment]
Yes, that's true ... we should definitely move some configurations from the installation to the sulu "core".
e.g. sylius:
https://github.com/Sylius/Sylius-Standard/blob/master/app/config/routing.yml#L1
https://github.com/Sylius/Sylius-Standard/blob/master/app/config/config.yml#L4

**Comment by wachterjohannes** [comment]
this would also affect the discussion about using sulu-standard https://github.com/sulu-io/sulu-standard/issues/633

**Comment by danrot** [comment]
@chirimoya Would be even more awesome to use [PrependExtensionConfigs](http://symfony.com/doc/current/cookbook/bundles/prepend_extension.html), because then the developer doesn't even have to think about including anything at all, only about the changes he wants to have.

Apart from that, I think the bundles should know about dependencies to other bundles and should bootstrap the configuration needed for them to work. This single configuration file already stops working as soon as a single bundle is deactivated, because the configuration component will fail loading due to missing bundle configuration descriptions.

**Comment by danrot** [comment]
@chirimoya Anything leftover we can do here? Or can we close that issue?
