### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by sagikazarmark** [sulu/sulu#2149]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |

Do you use any crowd source tools for translations? I would be happy to help with Hungarian translation.

**Comment by patkar** [comment]
https://crowdin.com would be cool :+1:

**Comment by sagikazarmark** [comment]
Agreed :+1:

**Comment by danrot** [comment]
@sagikazarmark We are thinking about using a crowd source tool, would definitely be awesome :-) But in the mean time you would have to do it like in https://github.com/sulu-io/sulu/pull/1905. For the french translation we have some people we can ask, for hungarian it will probably get difficult. We should maybe also define how we handle community based translations /cc @chirimoya @berndhep

**Comment by danrot** [comment]
For the new frontend I've been looking into this again, and I found following solution, whereby it is very likely that we will use it: https://lingohub.com/

However, have to check some more stuff and write a documentation for that, so I keep this ticket open.

**Comment by danrot** [comment]
This issue will also be very important for translating [our forms](https://github.com/sulu/sulu/blob/b747cdd/src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml#L27). Currently we only have the same options as in the XML configuration of the pages/snippets, which means the translations are directly written in there, instead of being used from our translation json file. The thing is that this way it is not possible to extend another language, because the entire form XML would have to be overwritten...

The idea is to have something like this:

```xml
<title>sulu_contact.salutation</title>
```

Then the system would translate this title, and it is very easy to add more languages.
