### ISSUE TITLE
Permissions update requires manual reload of page.

### ISSUE THREAD

**Issue by dantleech** [sulu/sulu#2256]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.0-RC4 |
| Browser Version | Chromium |
#### Actual Behavior

If you update the permissions ("User Roles") has no immediate effect. You need to manually reload the page (F5) in order to use the new permissions.
tes.
#### Expected Behavior

The permissions should either have an immediate effect or a banner should be shown asking the user to reload the page or similar.

**Comment by danrot** [comment]
Having an immediate effect would be quite hard, because e.g. navigation is never rerendered. But showing a label sounds like a good solution to me.

**Comment by alexander-schranz** [comment]
@danrot we should fix this for 2.0 should easier possible with react to reload the users config and permissions.

**Comment by danrot** [comment]
Not sure if it is that easy... And since this doesn't happen too oftern I am not sure if it is worth investing the time. Actually this issue is also resolved, because we have this banner mentioned above now :see_no_evil: We should probably clarify with @chirimoya when he's back from holiday what we do about this.
