### ISSUE TITLE
Redirect for internal link cuts query parameters

### ISSUE THREAD

**Issue by sabinebaer** [sulu/sulu#2261]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.1.10
| Browser Version | All

#### Actual Behavior

Requests to ```/``` are redirected to ```/{localization}``` without keeping query parameters.

E.g. ```www.mydomain.com/?myparameter=1``` redirects to ```www.mydomain.com/en```.

#### Expected Behavior

The query parameters should be added to the target domain.

E.g. ```www.mydomain.com/?myparameter=1``` should redirect to ```www.mydomain.com/en?myparameter=1```.

**Comment by danrot** [comment]
I have tested it, and for me it works as expected, as the following screenshot shows:

![image](https://cloud.githubusercontent.com/assets/405874/14356985/27bc578a-fce7-11e5-8aa3-1341c70e8e12.png)

After a short discussion with @sabinebaer we realized that this is caused because the startpage is an internal link. The question is if we should append the query string in that case.
