### ISSUE TITLE
Button Add in admin=>Asset menu does not work (javascript error)

### ISSUE THREAD

**Issue by ArturProd** [sulu/sulu#2444]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.3 (master) |
| Browser Version | Chromium Version 49.0.2623.108 Ubuntu 16.04 (64-bit) |
#### Actual Behavior

In the admin panel, when clicking on the Asset menu, then clicking on the "Add" button to add an asset, nothing happens.
#### Expected Behavior

I expect the add button would open a dialog to add an asset.
#### Steps to Reproduce

Login to admin panel, go to Assets menu, click the add button.
#### Possible Solutions

I don't know but there is a javascript error every time I click this button:

```
husky.js:46403 Uncaught TypeError: Cannot read property 'current' of undefined
addHandler @ husky.js:46403
jQuery.event.dispatch @ husky.js:7152
elemData.handle @ husky.js:6823
```

![image](https://cloud.githubusercontent.com/assets/5223932/15752721/a3c36c36-28ef-11e6-800e-c6449558fa1a.png)

![image](https://cloud.githubusercontent.com/assets/5223932/15752746/c3791d00-28ef-11e6-925d-98d33fc38a52.png)

**Comment by danrot** [comment]
Cannot reproduce, do you still have that problem?

**Comment by marcelmoosbrugger** [comment]
The problem has to do with the mysql 5.7 update (https://github.com/sulu/sulu/issues/1797). The Javascript-Error only occurs because the system can't finish the request for loading the collections. The server returns with the code 500 on "/api/collections?sortBy=title&page=1&limit=20" because of of the only-full-group-by mode of mysql 5.7 and doctrine not properly handling it.

A temporary workaround is to disable the only-full-group-by-mode on your machine:
https://www.sitepoint.com/quick-tip-how-to-permanently-change-sql-mode-in-mysql/

**Comment by danrot** [comment]
We are now MySQL 5.7 compatible, so this problem should not appear anymore.
