### ISSUE TITLE
*wish* validate webspace and pages 

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2445]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |

it would be good to have some tool to validate the config xmls because sometimes something is not well defined and there is no way to know, specially in the ajax requests for the admin that load the pages.
i.e. If a template of page view can't be found it simply doesn't load.

**Comment by wachterjohannes** [comment]
we could provide a console command which prints the error from a specific file. would that be enough? @danrot what do you think? shouldnt be to hard to add that.

**Comment by danrot** [comment]
Well, we can add a command for that but most people won't know about the command, and still have the same problem... I would say the real problem is that what's happening here is not really intuitive...

**Comment by alexander-schranz** [comment]
@danrot could we add something to the profiler?
Did see that the profiler also list missing translations. 
So maybe something like missing template files or failed template files.

**Comment by danrot** [comment]
@alexander-schranz Sounds interesting, and I think the chance is a lot higher that people are familiar with that :-)

**Comment by danrot** [comment]
We changed a lot of this stuff to throw exceptions instead of silently ignoring the error, so this should not be an issue anymore.

**Comment by Clindbergh** [comment]
> We changed a lot of this stuff to throw exceptions instead of silently ignoring the error, so this should not be an issue anymore.

@danrot I beg to differ. Here's an 

# Example

I ran into. Trying to add smart content, I copied the example code and adapted the title from the [smat content docs](https://docs.sulu.io/en/2.1/reference/content-types/smart_content.html). Here is the code snippet I ended up with:

```xml
        <property name="pages" type="smart_content">
            <meta>
                <title lang="de">Unterseiten</title>
            </meta>

            <params>
                <param name="provider" value="pages"/>
                <param name="max_per_page" value="5"/>
                <param name="page_parameter" value="p"/>
                <param name="properties" type="collection">
                    <param name="article" value="article"/>
                    <param name="excerptTitle" value="excerpt.title"/>
                    <param name="excerptTags" value="excerpt.tags"/>
                    <param name="excerptImages" value="excerpt.images"/>
                    <param name="excerptDescription" value="excerpt.description"/>
                </param>
                <param name="present_as" type="collection">
                    <param name="two">
                        <meta>
                            <title lang="en">Two columns</title>
                        </meta>
                    </param>
                    <param name="one">
                        <meta>
                            <title lang="en">One column</title>
                        </meta>
                    </param>
                </param>
            </params>
        </property>
```

The presented **exception** produced:

`[2020-07-22T08:02:01.449007+02:00] request.CRITICAL: Uncaught PHP Exception Sulu\Component\Rest\Exception\MissingParameterException: "Missing parameter token in Sulu\Bundle\PreviewBundle\Controller\PreviewController" at /home/httpd/vhosts/mydomain.ch/httpdocs/sulu-website/vendor/sulu/sulu/src/Sulu/Component/Rest/RequestParametersTrait.php line 38 {"exception":"[object] (Sulu\\Component\\Rest\\Exception\\MissingParameterException(code: 0): Missing parameter token in Sulu\\Bundle\\PreviewBundle\\Controller\\PreviewController at /home/httpd/vhosts/mydomain.ch/httpdocs/sulu-website/vendor/sulu/sulu/src/Sulu/Component/Rest/RequestParametersTrait.php:38)"} []
[2020-07-22T08:02:01.543918+02:00] security.DEBUG: Stored the security token in the session. {"key":"_security_admin"} []
`

Later I noticed that `<param name="present_as" type="collection">` does not have the correct language. The exception message was not helpful.

# 2nd example

> i.e. If a template of page view can't be found it simply doesn't load.

I tried this scenario. I created a page xml config, but no associated twig file. I opened sulu, created a new page and choose the new page type. I can edit the page and enter my information. Everything worked so far. An exception is only thrown, when I try to `save and publish` the page. 

`Uncaught PHP Exception RuntimeException: "Metadata for Structure Type "member789" was not found, does the file "member789.xml" exists?"`

This message is somewhat helpful, but does not exactly catch the mistake.

**Bottom line: The exceptions are not yet sophisticated enough to resolve this issue.**

Of course more work could be done to make exceptions more helpful. However I'd argue that there are clear

# Advantages of a `verify` command

* **Helpful errors**: With a sophisticated command, error can give very specific and helpful hints. Likely more than what exceptions can and should do. For example the [elm](https://elm-lang.org/) compiler does a [great](https://elm-lang.org/news/compiler-errors-for-humans) [job](https://elm-lang.org/news/compilers-as-assistants) at this. The cms would become **much more approachable** to newcomers.
* **Isolating errors**: When something doesn't work it could be due to caching, permissions or anything else. Having a command to validate the xmls would narrow down the potential reasons.
* **Fast detection**: It is much quicker to run a command to test the configuration, than it is to open sulu and try everything.
* **Early detection**: In some cases a misconfigured xml might make it into production and is only spotted when the client tries to edit the page. As `verify` would always test the entire xml, the probability for such a bug is decreased. To improve it even more, the command could be added to a...
* **Deployment workflow**: Requiring a successful completion of the `verify` command before each release could avoid some bugs.

> but most people won't know about the command

Introducing the command in the [book (chapter 'Create a page template')](https://docs.sulu.io/en/2.1/book/templates.html) and maybe add the message `Try running verify` to some of the most common exceptions caused by misconfiguration would change this.

**Comment by Clindbergh** [comment]
@danrot / @alexander-schranz / @wachterjohannes : Is this something that could potentially be reconsidered or out of scope?

**Comment by alexander-schranz** [comment]
@Clindbergh it should not crash when you forgot a language in your `present_as` it should fallback to the language which which was provided. Can you create an own issue for that?

There is a `bin/adminconsole sulu:content:validate:webspaces` which source code is [here](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php), feel free to create a pull request to extend it if you run into other cases. The 2nd example should be catched by that command and output you an error.
