### ISSUE TITLE
Different theme for each portal

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2469]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
#### Actual Behavior

Only one theme for each webspace can used.
#### Expected Behavior

It would be nice to be able to configure a theme for each portal.
Maybe this behavior could set for now with a condition in twig template so the right sub template will load according to the portal key, but it would be nice to be able to override the webspace template on different portals

**Comment by wachterjohannes** [comment]
that was one of the intentions we thought while we introduces the portals. we will plan this in one of the next releases /cc @chirimoya what do you think?

**Comment by piratadelfuturo** [comment]
I was able to set the template depending on the Portal with a configuration file data through a bundle extension... but I would have to override now some parts of the preview renderer, although that would have to be selected on the admin for better usability.

**Comment by danrot** [comment]
Our current ideas are going more into the direction of removing portals at some point... Everytime I see a project where that might get useful, people still decide against it, because they don't want to share the content tree. Therefore I am going to close this issue. But I am open to change my mind, if many people say that they are using this feature :slightly_smiling_face:
