### ISSUE TITLE
RequestAnalyzer error on wrong url

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2562]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2 |
#### Actual Behavior

if you go add two dashes on the url after the domain on a non-existent url in PROD: http://www.something.com//fr/asdasd

You get the following error:
![www_asdsadasda_con__fr_asasdda](https://cloud.githubusercontent.com/assets/466499/16664160/e2730ed2-444c-11e6-927e-a2ca3213cfa5.jpg)

**Comment by danrot** [comment]
Should probably show a 404 as it does in dev mode...

**Comment by danrot** [comment]
I am currently investigating this issue. The problem is that in the `prod` environment the system tries to render an error page, where the localization is required. But when you use the double slash as you have shown the system cannot find a portal with a language being connected (more on that later). It is working in the `dev` environment, because Symfony catches the error earlier, and shows the Symfony error page instead, which doesn't need a localization.

Sulu seems to work as expected, and [creates a new route](https://github.com/sulu/sulu/blob/b81a56e6357924d1ba8fd060bacdf5571ef6a8d6/src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php#L309) which is redirecting to the URL with the localization as intended. 

However, [Symfony](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L141) filters that route, because it's regex is only matching exactly `/`, although the pathinfo returns `//`.

And finally the route contains `/` instead of `//`, because the [Route class](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Route.php#L159) reduces them to a single `/`.

TBH I am not sure how we should solve that... Have to dig into it a bit further.

**Comment by danrot** [comment]
I think the biggest problem is that the slashes are trimmed in the `Route` class. Looks like Symfony does not really support that style of URLs. So we should probably handle them in a special way... The question is only which status code we return. `400` sounds like a reasonable choice.
