### ISSUE TITLE
Webspaces security contexts

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu#2576]
| Q | A
| --- | ---
| Bug? | maybe
| New Feature? | no
| Sulu Version | 1.2.5

#### Actual Behavior

I have 21 webspaces, and I added them sets of 7, but when I added the last set I can only se only two from the last set of 7, because the security context for them was not allowed for my user for VIEW.

This happened in my local machine as in my prod server, and I checked the webspaces XML multiple times, and they are valid and the webspaces are listed but just the view permission is not allowed.

This could be a bug?

**Comment by piratadelfuturo** [comment]
Oh well I just found out this exists, but I don't know why those had no permissions at all..

![sulu_-_settings](https://cloud.githubusercontent.com/assets/466499/16742857/b01f811c-4777-11e6-81c3-f5a77223130a.jpg)

**Comment by piratadelfuturo** [comment]
Just reopened to let you know about this behavior.

**Comment by danrot** [comment]
@piratadelfuturo Just to be clear: You can't set the permissions on the new webspaces? Because if you can set them it's not a bug. We don't wan every user to gain access immediately as soon as a new webspace is added. Otherwise it could be the same issue as https://github.com/sulu/sulu/issues/2477. We are just talking about a different screen here, and it should be fixed the same way as in the other issue: We should probably send a patch, and only send the values being really changed.

Can you still add what problem you exactly ran into?

**Comment by piratadelfuturo** [comment]
@danrot I am able to set the permissions, but it's just that when I added those new webspaces it had no permissions set as the image shows. and it took me a while to find out what was going in, maybe it just need to be in documentation that whenever you add a webspace you need to check the permissions.

**Comment by danrot** [comment]
@piratadelfuturo Have done that in https://github.com/sulu/sulu-docs/pull/252, will probably be merged soon.
