### ISSUE TITLE
Edit of extensions will also overwrite content or other extensions

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2619]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.2 |
#### Actual Behavior

The seo and excerpt tabs are saved over the same action as the content. So if you edit seo data it will also save the content data and will overwrite it. It appears a message that the data has been changed before but I think the content manager dont know that this save will overwrite the data of the content tab so he will mostly click overwrite because for him the current seo data is the correct one.
#### Expected Behavior

Every tab save should only change the data of the current tab.
#### Steps to Reproduce
1. Open Tab on Content Tab and Open Tab on Seo Tab
2. Change title on Content Tab and click save
3. Change something in the Seo Tab and click save
4. Message appear data has been changed and will be overwritten.
5. Click overwrite

**Comment by danrot** [comment]
I think this should not be an issue anymore, because the extensions only write in their namespace (at least if the [`page_excerpt.xml` file] is written correctly, but if somebody writes it differently I would say it is not our problem anymore. Otherwise we cannot even allow to split a form over multiple tabs. So I would close this issue.
