### ISSUE TITLE
Media Selection selected assets masonry not working when no images are selected

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#2659]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop (2016-07-22)

### Actual Behavior

![bildschirmfoto 2016-07-22 um 09 45 40](https://cloud.githubusercontent.com/assets/1698337/17050054/2613116e-4ff1-11e6-9946-7804d50065f2.png)

### Expected Behavior

Masonry should work correctly for documents.

**Comment by Jace25** [comment]
Maybe also related to https://github.com/sulu/sulu/issues/2540

**Comment by danrot** [comment]
@Jace25 TBH I don't think so... But can you answer my question in the issue you just linked? 😄

**Comment by Jace25** [comment]
@danrot, sorry!

With the latest sulu dev, i am able to add files, to save the article and i also could view them while editing:
![image](https://cloud.githubusercontent.com/assets/4090694/17130979/843d4142-531b-11e6-933c-91e7b7fbe1b2.png)

![image](https://cloud.githubusercontent.com/assets/4090694/17130983/8aef2f3c-531b-11e6-8b63-bf24e21cca92.png)

![image](https://cloud.githubusercontent.com/assets/4090694/17130999/988edc46-531b-11e6-9e6e-d1ba2d04ee92.png)

So i think this issue is solved somehow with the latest changes?
