### ISSUE TITLE
ContentBundle depends on AbstractKernel

### ISSUE THREAD

**Issue by sagikazarmark** [sulu/sulu#2738]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | develop

#### Actual Behavior

The following class relies on the AbstractKernel from the standard app:

https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/ContentBundle/Search/Reindex/StructureProvider.php#L83

#### Expected Behavior

There should be no such dependency.

#### Steps to Reproduce

Rename AbstractKernel to something else.

#### Possible Solutions

Change the context to a boolean value which helps to decide whether to execute the relevant code or not.

**Comment by danrot** [comment]
Actually the constants are defined in `Symfony\Component\HttpKernel\Kernel\SuluKernel`, so changing the line to this class would solve the problem. Would you mind creating a PR for that?

Changing to a boolean doesn't work, since there might also be even more contexts in the future (or it would maybe work at the moment with quite a big refactoring, but I also think it is less elegant).

**Comment by sagikazarmark** [comment]
> Would you mind creating a PR for that?

Yup

> Changing to a boolean doesn't work, since there might also be even more contexts in the future (or it would maybe work at the moment with quite a big refactoring, but I also think it is less elegant).

What if in the future you want more complex decision logic to decide this? IMO putting it into the Extension and setting a parameter would be better.

**Comment by wachterjohannes** [comment]
@sagikazarmark should be fixed. if not please reopen this issue.
