### ISSUE TITLE
Rotation image based on exif data after upload

### ISSUE THREAD

**Issue by rudott** [sulu/sulu#2767]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Sulu Version | dev master |
| Browser Version | All |
#### Actual Behavior

When upload an rotated image (from the camera) you will get an incorrect image. 
For example an photo contains in the exif data rotation: 90 but the image will be shown with rotation 0.
#### Expected Behavior

Image should be rotated with for example the usage of autoRotateFilter.
#### Steps to Reproduce

Upload an rotated photo which contains this exif data.
#### Possible Solutions

Possible solution, the usage of the auto rotate filter (from imagine):
https://github.com/liip/LiipImagineBundle/blob/6a017566e3dea75e10f8c2fb58ee621e863d83e6/Imagine/Filter/Loader/AutoRotateFilterLoader.php

**Comment by danrot** [comment]
That's actually a good input. Would this also be correct when the user has rotated the image in any other program beforehand?

**Comment by rudott** [comment]
@danrot Photoshop for example rotates an image by default (this is a setting). 

When you change the rotation by yourself the rotation metadata is removed (in most programs) and when you upload this is image, the image is displayed correctly.

Also when you only change dimensions of a photo the rotation data is maintained in for example Photoshop.

**Comment by alexander-schranz** [comment]
It shouldn't be much work to include this:
http://imagine.readthedocs.io/en/latest/usage/metadata.html. I also would store the metadata inside the `properties` of the fileVersion. To update old images to store the metadata an update metadata command can be added.

**Comment by danrot** [comment]
@alexander-schranz Interesting point, but I can't see how this can be used to update old images. We would have to write that on the old images, and since we introduce that probably together it doesn't apply to them.

But when thinking about this, do the original images lose this data in some way? If not it doesn't really make sense to write the data in the database, but can simply be read from the images itself.

**Comment by alexander-schranz** [comment]
the original uploaded file is never changed, so with update old images I mean to read the metadata from the original and store them in the DB. Thought the performance is better when we store them in our properties e.g. when someone want to read the GPS data to show where images was taken. But maybe it would be enough to make it just possible then he can store in the properties what he want and he can write his own service, because for this issue we can read them directly from the original file.

**Comment by alexander-schranz** [comment]
Implemented in #4236 available since 1.6.23
