### ISSUE TITLE
Creator and published are null in preview

### ISSUE THREAD

**Issue by ReneZumtobel** [sulu/sulu#2837]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3
| Browser Version | Browser name and version

#### Actual Behavior

If using {{ creator}} or {{ published}} then the preview is throwing an error because the values are null.

#### Expected Behavior

It should show the same value as in the Frontend or at least a default value.

#### Steps to Reproduce

 Write {{ dump(creator) }} in template and see that in the backend the value is null.

**Comment by wachterjohannes** [comment]
would be quite easy to fix. we only have to include this in the `preview` serialization group. but there are several others which are null like parent or children. i have tested this once before and the children makes problems because the `ChildrenCollection` has a service inside which cannot be serialized easily (maybe ignored and set by a listener or handler after deserialization).

**Comment by danrot** [comment]
@wachterjohannes There is a separate issue for the other collections: https://github.com/sulu/sulu/issues/2794
