### ISSUE TITLE
Change style-ci config for return null values

### ISSUE THREAD

**Issue by turbo-ele** [sulu/sulu#2906]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
| Sulu Version | 1.3.0 |
#### Actual Behavior

Currently style-ci changes all `return null` statements to `return;`, which conflicts with the symfony coding standards:
http://symfony.com/doc/current/contributing/code/standards.html#structure

```
Use return null; when a function explicitly returns null values and use return; when the function returns void values;
```
#### Expected Behavior

return void: `return;`

explicitly return null: `return null;`
#### Possible Solutions

Disable configuration for simplified_null_return in .styleci.yml: https://styleci.readme.io/v1.0/docs/fixers#simplified_null_return

```
disabled:
     - simplified_null_return
     ...
```

**Comment by danrot** [comment]
Sometimes it is probably hard to distinguish if it is returning null or void... Don't know if it helps to avoid confusion when we use this as described in the symfony standards....

**Comment by wachterjohannes** [comment]
i also thought about that because i see it a lot of times recently (maybe because of the discussion with @turbo-ele) but i think for developer and also "code-reader" it would be an improvement if we keep it this way. @danrot i understand your negative thoughts but in my oponion that would be a thing which should be solved in a "review" because it would also not be "clear" all the times.

**Comment by Spomky** [comment]
I agree with that as it may break some projects on PHP7.1 with a defined return type.

Example:

```php
/**
 * @param int $a
 * @return null|string
 */
function getFoo(int $a): ?string {
    if (0 < $a) {
        return 'Foo!';
    }
    return null;
}
```

**Comment by danrot** [comment]
Seems like it has been dropped from the default symfony preset in styleci anyway, so this issue can be considered fixed.
