### ISSUE TITLE
Copying language versions breaks external links

### ISSUE THREAD

**Issue by tobias47n9e** [sulu/sulu#2958]
| Q | A |
| --- | --- |
| Bug? | yes |
| Sulu Version | 1.2.7 |
| Browser Version | All |
#### Actual Behavior

Copying one language version to another (e.g. `en` -> `en-us`) causes external links to 404.
#### Expected Behavior

Copying should correctly create external links.
#### Steps to Reproduce

I have a site which has an internal link pointing at a page, which is an external link. This is used to show the external link on a page and also have it in the main navigation. When copying the whole language version to another one (e.g. `en` to `en-us`) then clicking on this link will redirect to the 404 page. This can be repaired by switchting the external link to `Content`, then save, then back to `External Link` and then saving again. This is easy to fix, but time consuming if a page has many external links.

**Comment by danrot** [comment]
@tobias47n9e Cannot (really) reproduce that issue. I have built the following structure:
![image](https://cloud.githubusercontent.com/assets/405874/20257280/c92e114e-aa48-11e6-98eb-9b0a0e37a3fc.png)

Test contains an internal link content type, which is containing a link to the page `Google`, which is an external link. Then I copied the language version from `Google`, and afterwards from `Test`, and the external links were shown correctly. The links on the website were showing directly to the external link, so there wasn't really a chance for our system to fail.

However, the only thing I can reproduce, is that there is no redirect from the external link page to the external URL, which makes sense, because the URL has never existed.

@chirimoya I think we agreed that this is the behavior to expect, isn't it?
