### ISSUE TITLE
Sulu internal format avoid cropping for new format

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#3038]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4

#### Actual Behavior

when create the following format its not available in the crop:

#### Expected Behavior

When the user define an own 400x400 it should be available in cropping so internal should be false there.

#### Steps to Reproduce

Create a format in `app/config/image-formats.xml`:

```xml
    <format>
        <name>400x400</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">400</parameter>
                    <parameter name="y">400</parameter>
                </parameters>
            </command>
        </commands>
    </format>
```

its not available in the cropping dropdown because I think it is still marked as internal.

**Comment by danrot** [comment]
I've tried to reproduce that, but at least in sulu-standard it's working. At least somehow. I think we should disallow the use of multiple format with the same key, because it also has unpredictable behavior in other situations:

1. The newly created format is also used for the contact image (because they share the same key), so the image is croppable.
2. The newly created is ignored as in your case, and can't be cropped at all.

In general it is not clear what happens when `uploads/media/400x400/...` is called. I think we should enforce the key to be unique, and throw an exception if it already exists. Maybe we can also rename the sulu internal formats to make that less likely.

/cc @chirimoya @wachterjohannes
