### ISSUE TITLE
Snippet copy-locale command does not copy the changes to live workspace

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#3079]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | ^1.3
| Browser Version | none

#### Actual Behavior

The command `sulu:snippet:locale-copy` copies the content only in the default workspace.

#### Expected Behavior

Publish the snippet automatically.

#### Steps to Reproduce

Create a snippet in `de` and run the command with `sulu:snippet:locale-copy de en` and see in phpcr:shell that the content is not in the live workspace.

#### Possible Solutions

Call publish after copy content.

**Comment by wachterjohannes** [comment]
Same problem seems to be in the `ContentLocaleCopyCommand` https://github.com/sulu/sulu/pull/3068/files#diff-bd5cb4edc92ad3a8d6bdc38c7e78b835R96

**Comment by danrot** [comment]
I'd say it is currently a bug for the snippets, because there is no drafting implemented. But I am not sure if the content should also be handled that way... Automatically publishing these changes would probably lead to duplicate content. (The same is true for the snippets, but the system is in an inconsistent state if we don't publish them)
