### ISSUE TITLE
Split user security

### ISSUE THREAD

**Issue by freddy1805** [sulu/sulu#3082]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.3.1
| Browser Version | Chrome MAC OSX

#### New Feature

I think it's better to split the security for the profile edit in sulu, because if you want to edit your own password you must have the user edit permission and then you can edit all profiles.
![bildschirmfoto 2016-12-13 um 10 28 35](https://cloud.githubusercontent.com/assets/16577848/21134694/5b53e804-c11f-11e6-975b-24bb53deadb3.png)

**Comment by danrot** [comment]
You are completely right... There is already a `ProfileController` which handles setting the user settings. This one should be extended to be also able to set things like a password or first and last name.

If you want to fix that, a PR would be welcome 😃

**Comment by andythorne** [comment]
I ran into this issue as well. I think the problem is more deeply rooted that being able to extend the controller.

The permissions system as it is works fine when we're defining role-based permissions (apart from in this case where users need decoupling from contacts), but we have no ability to define user permissions. So, in a user's case, they effectively don't have permission to view their own data. 
The same applies to articles, where your team has multiple editors and you want editors to be able to create and edit their own articles, but not others.

[Symfony ACL can handle this with ease](http://symfony.com/doc/current/security/acl_advanced.html). I don't know why, but there was a [AccessControl/SymfonyAccessControlManager.php](https://github.com/sulu/sulu/blob/master/src/Sulu/Component/Security/Authorization/AccessControl/SymfonyAccessControlManager.php) that kind of did that. Can anyone shed some light on why we moved away from Symfony ACL?

If we were to always provide a user context, then we can verify at a user+role level, rather than just a role.

**Comment by danrot** [comment]
Well, your problem is definitely not solved this way, because having permissions per user is a different problem.

It would also not be too hard to implement that without the Symfony ACL, we just didn't make use of that feature so far.

And yeah, we used to use the Symfony ACL, but it turned out not to be a good choice at all. I know that I am not the only developer, who doesn't like this specific component. The problem, that made us remove it all together was that it is not possible to write efficient queries to only load the entities the user is allowed to see, because there is no real connection between the rows from the ACL and our own entities.

**Comment by andythorne** [comment]
Thanks @danrot, I did a bit more research into Symfony ACL and can see that's is not going to be the solution as well. 

We can achieve it in the current implementation using voters then, when a vote will succeed if the user is the owner of the document.

We will also need to set the default decision in sulu-standard to `affermative` and `allow_if_all_abstain` to `false`:
https://github.com/sulu/sulu-standard/blob/develop/app/config/admin/security.yml#L3-L4

**Comment by alexander-schranz** [comment]
A Profile Overlay was implemented in Sulu 2.0 (#4615)
