### ISSUE TITLE
External Links don't copy with locale-copy

### ISSUE THREAD

**Issue by ollietb** [sulu/sulu#3121]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | N/A

#### Actual Behavior

When running `app/webconsole sulu:content:locale-copy eventstag en pt` I get the error

```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 2 passed to Sulu\Component\Content\Compat\StructureManager::wrapStructure() must be an instance of Sulu\Component\Content\Metadata\
  StructureMetadata, null given, called in /mnt/c/xampp2/htdocs/cms/vendor/sulu/sulu/src/Sulu/Component/Content/Mapper/ContentMapper.php on line 943 and defined
```

#### Expected Behavior

The nodes to all be copied from the source locale to dest locale

#### Steps to Reproduce

Create a page of type "External Link" in one language. Add a new language to the webspace, run initialize and then `app/webconsole sulu:content:locale-copy eventstag en pt`

**Comment by ollietb** [comment]
If I manually copy all the External Links in the admin section to the current locale then I can run the locale-copy command without overwrite and it works.

**Comment by wachterjohannes** [comment]
i have done a short research - the problem is the `ContentMapper` which only copies the content of the structure (defined by the xml-template).

see https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Content/Mapper/ContentMapper.php#L486

@danrot i only see the solution by serializing the srcDocument to array and using the PageForm to bind the array to the destDocument. what do you think?

**Comment by danrot** [comment]
Just tested, this seems to work now.
