### ISSUE TITLE
CKEditor should be resizable

### ISSUE THREAD

**Issue by reflexxion** [sulu/sulu#3151]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.4.5

#### Actual Behavior

Currently the CKEditor is resized about three lines on inserting content.
For long article contents the editor is too small to have a nice editing experience.

#### Expected Behavior

The editor should be resizable with some "grabber" (default browser behavior)

#### Possible Solutions

I did ask this question in slack and @wachterjohannes had an idea about that.

> so i have seen we internally deactivate the plugin `resize` and set the config `resize_enabled = false`. would you please add a issue for that? i will add some thoughts there maybe we will allow this in one of the next releases

**Comment by wachterjohannes** [comment]
* it would be this plugin: http://docs.ckeditor.com/#!/guide/dev_resize
* the 'resize_enabled' was set to `false`: https://github.com/massiveart/husky/blob/9ac8b5fd984b54be0c237c8158cb78058069a002/husky_extensions/ckeditor-extension.js#L44

in addition to this facts we have removed the plugin from the config https://github.com/massiveart/husky/blob/9ac8b5fd984b54be0c237c8158cb78058069a002/husky_extensions/ckeditor-extension.js#L127 and it cannot be added by the config of the component because of this line https://github.com/massiveart/husky/blob/9ac8b5fd984b54be0c237c8158cb78058069a002/husky_extensions/ckeditor-extension.js#L235

i think it was a conscious decision maybe because of the design. But it would be interresting to enhance the ckeditor-component to allow this.

/cc @danrot @alexander-schranz

**Comment by danrot** [comment]
I don't really think it was a concious decision, since we can also change the height of a text-area... I think it should be possible to resize the text-editor, the question is just how to design that. /cc @berndhep

**Comment by danrot** [comment]
We have now made the text editor grow to a maximum of almost the entire form, I think this behavior is very comfortable now. Therefore going to close this issue.
