### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by nicolas-bastien** [sulu/sulu#33]
Hi,

Would be great to have an online demo to test your project.

Thanks 

Nico

**Comment by valle6** [comment]
The demo pages isn't accessible. "The Email/Password combination is wrong." Does the cause continue being the change of password by users? I think some solution must be implemented, because this becomes a negative advertisement. What does someone win with this obstacle?

**Comment by danrot** [comment]
The issue is the same as described before... But @chirimoya has already created an own branch for the demo, maybe we could just comment out the password part for the update of the user? Would be quite a fast fix.

@valle6 For now I have reset the password manually, it should work again. Will hope we find a fast solution for this issue.
