### ISSUE TITLE
Filter by template in search query string parameter

### ISSUE THREAD

**Issue by dalailomo** [sulu/sulu#3334]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.4

#### Actual Behavior

Currently the way to perform a search is to pass a query string parameter like `/search?q=something` and this does a search all across the site.

#### Expected Behavior (?)

Is there any way to actually filter by 'template'? Let's say I have a template defined in `mytemplate.xml` with a key `mytemplate`, and then I could do something like `/search?q=something&template=mytemplate`

This obviously does not work but I would like to know if there is a way to do something similar (I cannot find something as such in the documentation).

Thanks!

**Comment by danrot** [comment]
Hey, sorry for the late reply...

In general what you are asking for is possible. We are indexing the template type with the special name `_structure_type` in our search index, and you can make use of that.

Simply extend or reimplement (and override the `sulu_search.controller.website_search` service) the functionality of our [`WebsiteSearchController`](https://github.com/sulu/sulu/blob/bbf308a/src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php). In your own controller you can extend the `$queryString`:

```php
$queryString .= '+(_structure_type:"default")';
```

Hope that helps 😃 But I don't think we will add that in the core, because in most cases this functionality doesn't make a lot of sense for us (usually the user doesn't really know which template he would have to look for, nor does he even realize the concept of templates).

I am closing this issue with this answer, but you can continue ask questions if something is not clear.

**Comment by dalailomo** [comment]
Cool @danrot, thanks for the reply 👍 .

I will give it a try! Thanks
