### ISSUE TITLE
Check for webspaces configuration changes

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3395]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

Example: After adding a new language to a webspace the developer needs to run `sulu:document:initialize`

#### Expected Behavior

Maybe implement a check which looks up if the configuration has changed. At least we should display a warning in the Sulu Admin interface.

**Comment by Swader** [comment]
Suggestion: add `locale:add` command to admin console, include auto-running the init afterwards, make this the recommended approach for adding locales in the docs.

**Comment by danrot** [comment]
While I am not a huge fan of commands touching configuration files, this also doesn't solve the problem completely, since everybody could still update the file manually.

I think we need to find a good place to throw an exception with a good error message. I've put some thoughts into this, and I think it would be the best idea to introduce a new `DocumentManager` subscriber which checks if the route node for the given language already exists, and throw an exception telling the developer that `sulu:document:initialize` should be executed.

In theory nobody should be able to run into the issue that the `sulu:document:initialize` command is ignoring a new language anymore this way, but I think to be on the safe side we should also change this check in the command to check if the localized route node already exists, instead relying on the properties of a node.

**Comment by danrot** [comment]
I don't think that we gonna fix that before a bigger refactoring, and after that the problem might disappear anyway. Therefore I am going to close this issue.
