### ISSUE TITLE
PHPCR Clean Up Command

### ISSUE THREAD

**Issue by trickreich** [sulu/sulu#3396]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | --
| Browser Version | --

#### Actual Behavior

Examples:
- When deleting a language from a webspace, the language still exists in the PHPCR data.
- When changing the key of the template, the Sulu Admin can possible crash.
- ....

#### Expected Behavior

The develop can run a clean up job to avoid such problem.

**Comment by danrot** [comment]
Another thing is that if you rename properties of a template you might end up with properties on PHPCR nodes which are not used anymore at all. These should also get deleted by this clean-up command, which would especially be useful before a online-going.

**Comment by Swader** [comment]
If this is related, I just ran into the problem of the disappearing webspace, which broke all routes on the webspace pages (articles still worked). This happened because I renamed my webspace after having initialized everything. To fix it, I had to run `build dev --destroy` which wiped all my data, less than a desirable side effect.

Recommend adding a command to rename a webspace which would walk through all references of the webspace in the code and in the database(s), without wiping people's data. Legacy names are something that should be changeable, in particular as apps go from development to production.

Additionally, the admin console should check if a change occurred - for example, if something would cause it to not have **any** webspace listed in the sidebar (as it does after a webspace name change), it should scream at the user saying "Whoa, you have no webspaces, did you rename it? Do you want me to rename all references to the webspace retroactively?"

I think this DX upgrade should be critical for 2.0 release.

**Comment by danrot** [comment]
Personally I would think that this behavior adds more confusion... I somehow don't expect a Symfony command to change the content of files I have programmed or configured. Also checking if there is no webspace in the sidebar would not go far enough for me: The problem would still persist if I have 2 workspaces and rename just one of them, but the check for an webspace would not fail.

I think there should be something like a validation service or subscriber, which would check if everything is alright at the very beginning (e.g. have all the webspace the data they absolutely need?). When thinking about it, this could happen on the cache warmup: Then it happens only once, and adds no performance overhead when the cache is already built. And if a webspace changes at least that part of the cache should be invalidated again, and the check can run again.

**Comment by mareksuscak** [comment]
I think this would be a super useful feature since lots of unreachable nodes accumulate in PHPCR after some time in development.

**Comment by wachterjohannes** [comment]
fixed with #7291
