### ISSUE TITLE
App_dev for development

### ISSUE THREAD

**Issue by nvdbeek** [sulu/sulu#3529]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6

Symfony has two apps, app.php and app_dev.php. For developent we prefer to use app_dev instead of one app where someone can forget to remove development settings for production. Why do you have choose to not implement the app_dev?

We are busy to implement Sulu in our existing projects, but when we load the admin panel then sulu cannot open /admin/bundles, cause we are on the url: example.com/app_dev.php/admin/bundles. He navigate then to /app_dev.php/admin/. When we go to production then he can find example.com/admin/bundles. 

For local development we prefer to use app_dev, and the posibility to use an base href to load the /admin/bundles for production, test and dev.

**Comment by danrot** [comment]
That's because it is a lot more convenient and less error-prone in our opinion. There's no way there will be a wrong URL somewhere because of somebody using the wrong front-controller. IMO it might also be confusing to newcomers.

And apart from that you better get used to it, because [Fabien's Blog](http://fabien.potencier.org/symfony4-directory-structure.html) already says that they are changing to have a single front controller as well 😉

For these reasons I am going to close this issue.
