### ISSUE TITLE
Mandatory fields make problem on sulu:build

### ISSUE THREAD

**Issue by patrick-tassa-cafpi** [sulu/sulu#3670]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.8

#### Actual Behavior

When trying to install my project on a new environnement, mandatory fields is required.

> [Sulu\Component\Content\Exception\MandatoryPropertyException]Property "infomercial_1_title" in structure "homepage" is required but no value was given.

#### Expected Behavior

Create the template with mandatory fields.

#### Steps to Reproduce

`php bin/adminconsole sulu:build dev`

**Comment by danrot** [comment]
Yeah, that's something we were running into as well... I've looked into it already, and the cool thing is that the [`StructureSubscriber`](https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php#L123) already has an option to ignore required fields.

So it might be worth testing if just passing that option to the [`WebspaceInitializer`](https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php#L114) (which is executed when initializing Sulu), and see if that helps. IIRC there were other problems afterwards, that's why I stopped. But if you are willing to look into that, a PR would be very welcome 😃

**Comment by JulianTrei** [comment]
I see this is still a thing. Workarounds are not hard, but is there a solution?

**Comment by wachterjohannes** [comment]
@JulianTrei sorry but there is no currently no progress on this

**Comment by tentwofour** [comment]
I was having this same issue; but only then the build arrived at the publish method. Adding the $persistOptions as the 3 argument to the publish() call at line 126: https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php#L126

Not sure if that's worth a PR to help solve this, or what any other repercussions of doing this might be though...

Separate note, migrating my first project over to Sulu; very impressive and dev-friendly system, so thank you!

**Comment by danrot** [comment]
#4106 already started solving this issue, but somehow @hgiesenow didn't finish it... feel free to take over :slightly_smiling_face:

**Comment by tentwofour** [comment]
I will attempt, give me a bit to delve into the depths (currently figuring out how to migrate an existing site via fixtures; you'll probably see me on Slack soon, ha!)

**Comment by danrot** [comment]
Fixed in #4106
