### ISSUE TITLE
Colon in sulu:media and sulu:link breaks CKEditor's Advanced Content Filter

### ISSUE THREAD

**Issue by bixelsnl** [sulu/sulu#4006]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.19
| Browser Version | Google Chrome OSX Version 66.0.3359.181 (Official Build) (64-bit)

#### Actual Behavior

The colon in `sulu:media` and `sulu:link` breaks CKEditor's Advanced Content Filter.

#### Expected Behavior

I would like to be able to use the Advanced Content Filter while also keeping the media-link and internal-link plugins enabled.

#### Steps to Reproduce

I want to limit CKEditor to only allow bold, `sulu:media` and `sulu:link` tags. I want to do this using the Advanced Content Filter (https://docs.ckeditor.com/ckeditor4/latest/guide/dev_advanced_content_filter.html). In my template, I add the following:

```
        <property name="article" type="text_editor">
            <meta>
                <title lang="en">Article</title>
                <title lang="nl">Artikel</title>
            </meta>
            <params>
                <param name="allowed_content" value="b sulu:media[*] sulu:link[*]" />
            </params>
        </property>
```

When viewing that template in /admin, clicking the textarea initializes the RTE and leads to the following error in my JS console:

```
Uncaught TypeError: Cannot read property 'styles' of undefined
    at CKEDITOR.filter.check (husky.js:21190)
    at CKEDITOR.filter.addFeature (husky.js:21188)
    at addFeature (husky.js:21227)
    at f (husky.js:21878)
    at h (husky.js:21879)
    at a (husky.js:21879)
    at a.<anonymous> (husky.js:21884)
    at a.h (husky.js:21003)
    at a.<anonymous> (husky.js:21004)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (husky.js:21006)
```

Digging deeper, this happens because CKEditor does not allow `:` in tag names as per this regex:

https://github.com/ckeditor/ckeditor-dev/blob/4.4.7/core/filter.js#L1373

Version 4.7.7 is the version that is currently bundled with husky, but the regex is unchanged in newer CKEditor versions:

https://github.com/ckeditor/ckeditor-dev/blob/major/core/filter.js#L1398

Though even if I add the `:` in there manually, I do get a different error. But I think that may be unrelated- lets take it one step at a time.

Note that dashes in tag names are allowed, as per https://dev.ckeditor.com/ticket/12501

#### Possible Solutions

* We could change `:` to `-` in our own tag naming, though this would be a breaking change
* We could ask CKEditor to add support for `:` in tag names
* We could patch our bundled CKEditor to allow `:` 👎 

Curious about any other suggestions to make this work.

**Comment by choonge** [comment]
I think the cleanest option would be to rename the tag without any special characters at all, so `<sulumedia>` and `<sululink>`. Quoting from https://www.w3.org/TR/html5/syntax.html#tag-name:

```
Tags contain a tag name, giving the element’s name. HTML elements all have names that only use alphanumeric ASCII characters.
```

**Comment by wachterjohannes** [comment]
@choonge sorry for the delayed answer - the problem with this issue is, that all possible solutions to fix it (e.g. changing the name) is a breaking change and cannot be done in 1.6 release cycle. @danrot will take a look at it in the next bigger release 2.0

As we do not use `allowedContent` in the core we are unhappy to say that this won't be possible in the  current release.

**Comment by choonge** [comment]
@wachterjohannes No problem, thanks for your response. I understand the BC is problematic and that this won't be possible in 1.6.

For the moment, I saw that it is possible to revoke the 'View as Source' button permissions in the Roles screen. So with this, at least we can deny our editors the possibility to add script tags, or iframes, or other weird stuff. Combined with instructions to use Paste from Word for all their pasting, we have somewhat managed to prevent editors from messing things up unintentionally. So that's our work-around for now.

**Comment by danrot** [comment]
The colon has been converted to a dash in #4494
