### ISSUE TITLE
Allow to set a object security for other systems than Sulu itself

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4051]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

Currently its not possible to set a media to be private or secure over the UI.

#### Expected Behavior

It should be possible to set the media to be private.

#### Possible Solutions

**A. Add a private flag to the media**
**B. Add a private flag to the collection**

Private medias will not have the possibility to generate preview images.

#### Open questions

 - How to make the media downloadable for admin users?
 - When security is on collection it will be insecure when moving it into another collection?
 - When security is on collection what happens with the child collection?

**Comment by alexander-schranz** [comment]
Today I had a the discussion with @danrot and @c00n84 that the media should not only have a private flag, but also have the possibility to be role based. This should not only be based on roles in the admin security also for the website security. So users logged in e.g. using the sulu community bundle should be able to download specific medias and not loggedin users should get a 401 or if loggedin but no permisson a 403 error.

For this the media would need a Permission tab which maybe have a section per security system e.g.:

```
----------------------------------------------------

Sulu

Admin Role 1 [View] [Edit] [Remove] [Publish]
Admin Role 2 [View] [Edit] [Remove] [Publish]

----------------------------------------------------
Website

Website Role 1 [View]
Website Role 2 [View]
Website Role 3 [View]
```

**Comment by danrot** [comment]
First of all, I think I am going to rename that issue to something with website security, because this affects not only media, but should also be possible for e.g. pages (and it should feel very similar I guess).

After another discussion with @chirimoya a few more questions came up:

1. How do we handle frontend security in the administration UI? Each webspace can have its own security system, which should probably also show up in the permission tab (or in separate tabs?). Also, we have to think how to handle anonymous users. Either there is an anonymous group included in the permission tab, which is not represented by any role in Sulu, or the security for the given system has to be activated using a checkbox. If the checkbox is not ticked all users, including anonymous ones, have permissions for these entities. An advantage of the latter would be that we could also use this for Sulu's internal permissions, because if you set those currently, it is not possible to revert to the default permissions from the system.

2. How to handle caching? That could probably be solved with the [User Context Feature of the FOSHttpCacheBundle](https://foshttpcachebundle.readthedocs.io/en/latest/features/user-context.html), at least for pages. Media are a little bit of a different topic, because secured media cannot be stored on the file system and delivered by the webserver as it is currently done. (Maybe we can deliver them using the User Context caching as well?)

3. There is a separate issue on inheritance: #2391 - therefore the solution for this issue will not include any inheritance of permissions at all.

4. We have to think about which other parts of Sulu are affected by this. What came to our minds immediately were:
    - Smart Content
    - All selection field types
    - Navigation
    - Teasers

**Comment by alexander-schranz** [comment]
As discussed with @danrot and @chirimoya, we came to the solution that object security should always be activated also for the sulu system.

So every relevant Security System should be displayed on the Permission tab with a toggler.
The toggler will enables object specific permission and then the roles are displayed for that system where you can add permission to them.

E.g.:

----------------------------------------------------

Sulu [Toggler]

Admin Role 1 [View] [Edit] [Remove] [Publish]
Admin Role 2 [View] [Edit] [Remove] [Publish]

----------------------------------------------------
Website [Toggler]

Website Role 1 [View]
Website Role 2 [View]
Website Role 3 [View]

A more specified design will be discussed with our designer.

**Comment by danrot** [comment]
I just want to mention, that this would also solve the problem that the set permissions on a specific page currrently cannot be reverted to the permissions set for this section. With this approach that would be easily possible, and would not require the content manager to always copy the permissions to pages that have already a different permission set.

**Comment by alexander-schranz** [comment]
So I just want to document different cases which we need to check:

**Case A**

As a content manager I want that my uploaded media are available for all users. 
In this case the media collection has no security active and the media are provided always over the website urls in all cases.

AdminSecurity: false
WebsiteSecurity: false
Image Format Cacheable: true

| Current Context | Media Url | Media Website Url | Media Admin url
|-----------------|-----------|--------------------|-----------------------
| admin                 | website    | website                   | website
| website              | website   | website                   | website

**Case B**

As a content manager I want to protect media uploaded over the form bundle and get a in the email which is sent from the website context with links to the admin url. This is the case why we need the possibility to link media with admin url in the website context.

AdminSecurity: false
WebsiteSecurity: true
Image Format Cacheable: false

| Current Context | Media Url | Media Website Url | Media Admin url
|-----------------|-----------|--------------------|-----------------------
| admin                 | admin        | website                   | admin
| website               | website     | website                   | admin


**Case C**

As a content manager I want to protect media on the website and make them available for specific roles on the website.

AdminSecurity: false
WebsiteSecurity: true
Image Format Cacheable: false

| Current Context | Media Url | Media Website Url | Media Admin url
|-----------------|-----------|--------------------|-----------------------
| admin                 | admin        | website                   | admin
| website               | website     | website                   | admin

**Case D**

As a content manager I want to protect media for specific roles on the admin but they should be available in website.

AdminSecurity: true
WebsiteSecurity: false
Image Format Cacheable: true

| Current Context | Media Url | Media Website Url | Media Admin url
|-----------------|-----------|--------------------|-----------------------
| admin                 | admin        | website                   | admin
| website               | website     | website                   | admin


**Case E**

As a content manager I want protect media for specific roles on website and admin.

AdminSecurity: true
WebsiteSecurity: true
Image Format Cacheable: true

| Current Context | Media Url | Media Website Url | Media Admin url
|-----------------|-----------|--------------------|-----------------------
| admin                 | admin        | website                   | admin
| website               | website     | website                   | admin

**Comment by danrot** [comment]
I am about to implement the security for the website part, currently looking at the navigation. When rendering the navigation using e.g. the `sulu_navigation_root_tree`function, the following classes/methods are involved (being called in that order):

1. [`NavigationTwigExtension::treeRootNavigationFunction`](https://github.com/sulu/sulu/blob/caf2dd2ff5a93879aa0fb78100a48e1fdf8f6cde/src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/NavigationTwigExtension.php#L78)
2. [`NavigationMapper::getRootNavigation`](https://github.com/sulu/sulu/blob/caf2dd2ff5a93879aa0fb78100a48e1fdf8f6cde/src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationMapper.php#L103)
3. [`ContentQueryExecutor::execute`](https://github.com/sulu/sulu/blob/caf2dd2ff5a93879aa0fb78100a48e1fdf8f6cde/src/Sulu/Component/Content/Query/ContentQueryExecutor.php#L49)
4. [`ContentMapper::convertQueryResultToArray`](https://github.com/sulu/sulu/blob/caf2dd2ff5a93879aa0fb78100a48e1fdf8f6cde/src/Sulu/Component/Content/Mapper/ContentMapper.php#L611)
5. [`ContentMapper::rowToArray`](https://github.com/sulu/sulu/blob/caf2dd2ff5a93879aa0fb78100a48e1fdf8f6cde/src/Sulu/Component/Content/Mapper/ContentMapper.php#L644)

The last function call (`rowToArray`) loads a document and returns an array, so that function would have all the information we need in order to filter out pages the user has no sufficient permissions for. The only thing missing is a reference to the `User` itself, which we would need to call the [`AccessControlManager::getUserPermissionByArray` method](https://github.com/sulu/sulu/blob/caf2dd2ff5a93879aa0fb78100a48e1fdf8f6cde/src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php#L99). Using the result of that method call we could determine if we should include the result or not.

Now we just have to figure out, where we should include the user. I would say we do that in the `NavigationTwigExtension`, since we could pass the user in a similar way as the webspace or locale. Then the consecutive functions could also be called with a different user, in case this will be necessary at some point (maybe for a user impersonation feature).
