### ISSUE TITLE
SitemapProvider - Disable creating sitemap for particular portal

### ISSUE THREAD

**Issue by patrick-tassa** [sulu/sulu#4327]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6
| Browser Version | All

#### Actual Behavior

I use SitemapProvider to generate custom sitemap for particular portal.
Custom sitemap is created for all site portals. But when we have `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml"/>`, Google Search Console give us a syntax Xml error.

#### Expected Behavior

To not created custom sitemap if i don't need to avoid error in Google Search Console.

#### Steps to Reproduce

Implements SitemapProvider.

**Comment by danrot** [comment]
@patrick-tassa Most of the issues should be created in `sulu/sulu`, since most of the code is here. Issues only go into sulu-standard or sulu-minimal if they are really related to the boilerplate code that is there. Moved it now for you, but please keep that in mind for the future :slightly_smiling_face:

**Comment by alexander-schranz** [comment]
When a sitemap provider returns now `0` as maxPage which is the case when it have nothing in it the sitemap is not longer [shown](https://github.com/sulu/sulu/blob/d2442fbf5bc217dd2ec6be6db2d5a640de08aff6/src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRenderer.php#L68-L70) in the sitemap index so no empty sitemap will be render any more.
