### ISSUE TITLE
A type like "first subpage" for page settings

### ISSUE THREAD

**Issue by rogoit** [sulu/sulu#4355]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2
| Browser Version | Browser name and version

#### Actual Behavior

How does Sulu behave at the moment? 
Page seetings to internal page can only set to specific page

#### Expected Behavior
A type like "first subpage"

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by danrot** [comment]
We have talked about this, and we think it makes stuff more complex than necessary and hard to explain. E.g. what happens if pages are reordered? It might not be clear afterwards to the content manager that a link in the navigation leads to a complete different page then.

Additionally the current solution is not too complicated (creating an internal link and explicitly link it to the page you wish to show in the navigation) and it is more explicit, resulting in less confusion for the content manager.

**Comment by rogoit** [comment]
So I know this as a CMS standard feature on TYPO3 and other CMS. When pages are reordered the first page will be taken. This makes sense, when you have no overview page or want to push a page. This is a good feature on navigation with a second level. Them you can just press the main navigation item. This is a much easier UX handling.

**Comment by danrot** [comment]
I am sorry, but I think that's where we disagree. It might be easier in the beginning, because it saves you from explicitly creating an internal link to a certain page. But it definitely makes stuff harder to understand afterwards. If another content manager now changes the order, he certainly does not expect that a navigation item changes as well. Therefore we recommend the more explicit approach here, which does not have any drawbacks like this (except for a few more initial clicks, which pay back in the long term).
