### ISSUE TITLE
Custom Page Types or Folder 

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#4356]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2.0
| Browser Version | All

#### Actual Behavior

There are currently 3 Page Types in Setting ( Content , Internal Link o External Links) 

#### Expected Behavior

Sometimes many pages are created at same level that it would be interesting to be able to group in folders. It is not possible now to create custom Page Types and define their behaviour ( slug for childrens, redirect to previous page , etc .. )

#### Steps to Reproduce

Edit a page and go to setting section

**Comment by danrot** [comment]
We have talked about this, and came to the conclusion that this feature contradicts some of our basics too much. The reasons we have decided to not implement this include:

1. We say that the page tree shows the exact structure of the website, which would not be entirely true anymore
2. If you have a lot of pages on the same level, you probably should be looking into our [SuluArticleBundle](https://github.com/sulu/SuluArticleBundle), which was exactly built for that use case. Instead of a tree you have a flat list of articles there, including filtering and search functionalities, which make it much more comfortable to use with many items.
3. You could mitigate what your problem by using a different setting for our [ResourceLocators](http://docs.sulu.io/en/2.0/book/webspaces.html#resource-locator-optional)
4. It would also be hard to explain what happens when changing the type from page to folder and vice versa (would it immediately update all URLs?)

For this reasons we decided not to implement this.
