### ISSUE TITLE
Cannot copy/move content between webspaces

### ISSUE THREAD

**Issue by debreczeniandras** [sulu/sulu#4502]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6.25
| Browser Version | irrelevant
| Introduced with issue |  #2104

#### Actual Behavior

Can not copy/move content between webspaces.

#### Expected Behavior

Would like to copy/move content between webspaces.

#### Steps to Reproduce

- Set up two webspaces; 
- create content in either of them
- use the column navigation dropdown context menu and select copy/move

Only the tree of the current webspace is displayed.

#### Possible Solutions

The responsible line of code is here:

https://github.com/sulu/sulu/blob/ae060d1b1403f789653cff5c2478da5154a6b04a/src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/column/main.js#L610

When "webspace-nodes=all" is used (instead of 'single'), then all webspaces are listed, allowing to copy/move pages between them freely.

Is it deliberately pre-configured to only allow copying/moving content within the same webspace?

When not, can we change the default behaviour to list all configured webspaces in the tree?

The page selection within the teaser selection content type already lists the complete tree - including all webspaces.

#### Use case

I have a 'Staging' and a 'Production' webspace in one CMS that allow the website editor to test out content in the Staging webspace (on its dedicated hostname) and when done, copy/move the changes/new pages to the Production webspace, draft/preview it and when all is fine, publish it.

A kind of 'Content Staging' solution that is not available in sulu.

**Comment by wachterjohannes** [comment]
would it work when you set the parameter to `all`? have you checked this?

**Comment by debreczeniandras** [comment]
Yes, it works flawlessly with 'all'. 
It lists the tree (including all webspaces), and the copy/move also works thereafter.

**Comment by alexander-schranz** [comment]
I think copy would not be a big problem unless the target webspace has the same templates, only question is what should happen when the target webspace does not implement the template.

Moving I think need to be tested more if there is no problem with the History Redirects or if its visible in the Url History thats a Url of another webspace?

**Comment by debreczeniandras** [comment]
> unless the target webspace has the same templates

You mean **as long as** the target webspace has the same template, am I correct?
___

These are templates that should match?

``` XML
    <default-templates>
        <default-template type="page">default</default-template>
        <default-template type="home">default</default-template>
    </default-templates>
```
If yes, what can happen if these don't match?
___

The history is not visible in the target webspace after moving from another webspace, since the history is webspace-specific.

Is that a problem?
I think it's not expected to redirect old pages from a source webspace to a target webspace when moving a content. It starts a new history in the new webspace.

Perhaps the history url can be moved as well, but not considering the old webspace. (i.e. not redirecting from the old url to the target url.)

What do you think?

**Comment by wachterjohannes** [comment]
@alexander-schranz thought about the XML/Twig templates if the current template of the page which is copied/moved is not implement in the new webspace it could be a problem.

if you move a page from one webspace to another i would expect that the old url in the old webspace will redirect to the new one in the new webspace.

**Comment by debreczeniandras** [comment]
According to the [documentation](http://docs.sulu.io/en/latest/book/templates.html) and also the way I implemented it, templates are defined in these folders: 

- app/Resources/views/templates, 
- app/Resources/templates/pages. 

Thus, they are shared between all the defined webspaces. Or am I missing something?
Is there a way to actually define templates only for a specific webspace and not for another in one sulu installation? I thought that's the whole idea of multipel webspaces.
___

As for the redirecting and history across webspaces, I will check my local fork what's stored about the old url and what is available.

**Comment by wachterjohannes** [comment]
if you dont use the SuluThemeBundle thats correct - but when you install this bundle you can have different themes in different webspaces by implementing the twig template (in the other webspaces the template wont be available)

**Comment by danrot** [comment]
I will start working on this for Sulu 2.2 (at least the copying part), and therefore going to summarize what problems might arise from what I've read in this issue:

1. **Moving is way harder to implement, because of the route history.** Although I am not sure if this is true, since AFAIK the routes are linked by the UUID of a PHPCR node, therefore it might even already work (not tested). However, this does not have a priority for us right now. The history should not be webspace-specific as @debreczeniandras suggested, because that would result in some dead links, which is bad because of search engines.
2. **There might be issues when copying to another webspaces where the template of the page to copy does not exist.** Either we forbid that or (our prefered solution) the content manager can choose another template in the process. Then we would copy over all the properties that also exist in the other template.
3. A (maybe) more common issue would probably be **the problem of having different localizations between the two webspaces**. We could just ignore the fact, and copy over the entire node (the same thing could be done for point 2 instead of creating some complicated mapping code), or somehow implement to only copy over the languages that exist.

Regarding the proper solution, the equivalent of what you have suggested above (setting the `webspace-nodes` query parameter to `all`) would be removing the `options` prop of the copy overlay in the `List` container component of Sulu 2:

https://github.com/sulu/sulu/blob/6793028c2aa0340c85cfe03560c54b73f4a2274f/src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js#L681-L695

Just doing that would already show all webspaces in the copy overlay for pages, and copying the page would also already work (at least for the main case, didn't test the edge cases mentioned above yet). However, **that might be break stuff for some people**, when they are using the list view and call the `addRouterAttributesToListRequest` method on its builder. Then this parameter would be passed also to the copy overlay currently, but not anymore after this change, resulting in an unintented change for the copy dialog for other entities as well.

**Comment by danrot** [comment]
After a bit of thinking I am wondering if the suggestion that the content manager chooses another template in the process can work. The template can be different for every single locale of the page, so if that must work, we would have to show a dropdown for every locale in which a template is set, that does not exist in the target webspace.

An alternative approach would be to copy the page immediately without any comment, and move the choosing of that template when the user tries to open that page in the other webspace. That is something that should be implemented anyway, since also in other situations a page might be using a template that does not exist anymore in its webspace.

**Comment by danrot** [comment]
Result of a short call with @chirimoya:

> 2. **There might be issues when copying to another webspaces where the template of the page to copy does not exist.** Either we forbid that or (our prefered solution) the content manager can choose another template in the process. Then we would copy over all the properties that also exist in the other template.

Instead of fixing the template immediately, we will just copy the page. The template can be fixed when the page is opened. That the page does not have a template existing in that webspace should be shown somehow in the UI. As mentioned in my [previous comment](https://github.com/sulu/sulu/issues/4502#issuecomment-681640055) this solves this problem for many different use cases, and also works for pages with multiple localizations.

> 3. A (maybe) more common issue would probably be **the problem of having different localizations between the two webspaces**. We could just ignore the fact, and copy over the entire node (the same thing could be done for point 2 instead of creating some complicated mapping code), or somehow implement to only copy over the languages that exist.

When copying to another webspace, we should only copy the locales that exist in the target webspace (the PHPCR nodes just get cluttered otherwise for no good reason)

**Comment by alexander-schranz** [comment]
> Regarding the proper solution, the equivalent of what you have suggested above (setting the `webspace-nodes` query parameter to `all`) would be removing the `options` prop of the copy overlay in the `List` container component of Sulu 2:
> 
> https://github.com/sulu/sulu/blob/6793028c2aa0340c85cfe03560c54b73f4a2274f/src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js#L681-L695
> 
> Just doing that would already show all webspaces in the copy overlay for pages, and copying the page would also already work (at least for the main case, didn't test the edge cases mentioned above yet). However, **that might be break stuff for some people**, when they are using the list view and call the `addRouterAttributesToListRequest` method on its builder. Then this parameter would be passed also to the copy overlay currently, but not anymore after this change, resulting in an unintented change for the copy dialog for other entities as well.

Not sure about this change I think if I use `addRouterAttributesToListRequest` I also want that the parameters are given to copy and move list requests. But if there is currently no other way I would atleast add a comment why we removed that the options are added to the copy request.

**Comment by danrot** [comment]
I mean another approach to this would be to introduce another `addRouterAttributesToCopyListRequest` or something like that. Then it would at least be possible to still add some options if you want to. Although that would still be a breaking change, and we could also introduce that later if somebody complains about it.

**Comment by alexander-schranz** [comment]
@danrot that would be the best solution having a `addRouterAttributesToCopyListRequest`.
