### ISSUE TITLE
GLOB_BRACE breaks Sulu on Alpine Linux

### ISSUE THREAD

**Issue by tvwijgerden** [sulu/sulu#4513]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-alpha5
| Browser Version | n.a.

#### Actual Behavior

Sulu crashes on systems which don't support GLOB_BRACE.

#### Expected Behavior

Sulu works on systems that don't support GLOB_BRACE.

#### Steps to Reproduce

Install Sulu 2.0 on Alpine Linux.

#### Possible Solutions

In the SuluKernel use the Glob polyfill provided by the zendframework/zend-stdlib package.

**Comment by alexander-schranz** [comment]
@tvwijgerden Thank you for your issue.

The problem seems to be here: 

https://github.com/sulu/sulu/blob/d8f2b82faf4601e119d834c5de90c8b0e84ba91e/src/Sulu/Component/HttpKernel/SuluKernel.php#L109-L110

If GLOB_BRACE is not available we should fallback to the symfony function e.g.:
 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Config/Resource/GlobResource.php#L150-L151

you want to give it a try and create a Pull Request?

**Comment by tvwijgerden** [comment]
Yes, I'll create a Pull Request

**Comment by alexander-schranz** [comment]
@tvwijgerden awesome 👍 
Maybe we can directly use the `GlobResource` class of symfony so we don't need to handle the fallback ourself.
