### ISSUE TITLE
Create a Contact Selection Content Type

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu#4807]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | for 2.0
| Browser Version | -

#### Actual Behavior

Currently there exist no `contact_selection` content type.

#### Expected Behavior

There should exist a `contact_selection` content type.

#### Possible Solutions

**1. Create a ContactSelection Content Type similiar to.**

Here it can have a look at the [SingleContactSelection](https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/Content/Types/SingleContactSelection.php) or [ContactAccountSelection](https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/Content/Types/ContactAccountSelection.php)

**2. Register the selection field type:**

Register a selection field type here: https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php#L149

Have here a look at [SnippetSuluExtension](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php#L59-L76)

**3. Write a basic Unit Test for the ContactSelection**

Create a Unit Test for it

Have a look at [SingleContactSelectionTest](https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleContactSelectionTest.php)

**Comment by kfrohwein** [comment]
I guess this issue is obsolete in regards of the ContactAccountSelection Content type? 

https://docs.sulu.io/en/2.0/reference/content-types/contact_account_selection.html

**Comment by kfrohwein** [comment]
https://github.com/kfrohwein/sulu/tree/feature/4807_Contact_Selection_Content_Type Sorry I am not used to do upstream pull requests on github. How do I create a pull request that ends up in this issue? Or was the now closed pull request above okay?

And I messed up that it is still WIP. I have to write tests. Still from my hands on tests it works.

Wasn't so complicated in the end :)

Some things I don't understand:

Where do you register ContantAccountSelection? Should be in content.xml I guess but it's not and I can't find it.

`'overlay_title' => 'sulu_contact.contact_selection_overlay_title',`
`'label' => 'sulu_contact.contact_selection_overlay_title',`

In all other content types there is no 'label' set. But symfony told me I am demanded to set it. No clue why.

What is importData and exportData for in the ContactSelection Class?
And I removed from the class all I expected to be unnecessary in this case. Like "preResolve" and "getDefaultParams" Is that okay?

This is still no SimpleContentType I guess because it uses an array?

**Comment by alexander-schranz** [comment]
@kfrohwein the issue is not obsolete as you sometimes only want to select a contact or account not both. Export should convert the array into a JSON string array and the Import should the JSON string array write back to the database see the linked example its just json_encode and decode. And preresolve as linked above oriented here by the exist [single content type](https://github.com/sulu/sulu/blob/release/2.0/src/Sulu/Bundle/ContactBundle/Content/Types/SingleAccountSelection.php#L110) you just need todo a loop and add it to the reference store.

**Comment by danrot** [comment]
Regarding creating a Pull Request: You can't make this issue a Pull Request, that's not possible. Instead you create a new PR, and in our PR template there is a section called "Fixed Tickets", where you write something like "Fixes #4807", github will create the collection then.

**Comment by nnatter** [comment]
Fixed via #5383
