### ISSUE TITLE
Duplicates can be created when working with drafts (save and not publish)

### ISSUE THREAD

**Issue by GlennVL91** [sulu/sulu#4822]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | adcfb1b5c4aa3d40a8adde5e2c2579d1aa8fc601
| Browser Version | all

#### Actual Behavior

When u create a new page as a concept, so u don't publish it, the url is not automatically changed with a number. If u create multiple pages with the same title and so the same url and u want to publish them later, it says the location is not valid. Because of the duplicate. 

#### Expected Behavior

When u are creating a page with the same title and same url, add a number to the url as you would do when actually published.

#### Steps to Reproduce

Create concepts (save without publishing) with the same title (and also same url). Try to publish them later. The first one will be published, the second one will not because of duplicate.

#### Possible Solutions

When u are creating a page with the same title and same url, add a number to the url as you would do when actually published.

**Comment by danrot** [comment]
We are using the term "draft" instead of "concept", just saying that to avoid any confusion :slightly_smiling_face:

There are some technical reasons why what you are suggesting is a little bit hard to realize... The URLs are not really created until a page is published, because that's how we make sure that the URL does not show anything on the website as long as only the draft is existing.

Personally I would also prefer to get rid of this automatic numbering all together (at least in the UI, imports might be a different story). Usually we often get complaints that there is "-1" added in the URL, and content managers are not always aware why this is happening. I would prefer to just tell the content manager that the URL is already used, and that he has either to think about a different one, or delete the other occurence first, so that this is a more conscious decision.

Apart from that, what you are describing is IMO an edge case... Did that happen in a real project, or were you just playing around in an installation? Usually there are not two pages called the same sharing the same parent, and that's the only situation where you could run into troubles like this.

**Comment by GlennVL91** [comment]
This is an actual question of one of our customers who is using SULU to create news items on their website. They first create a few drafts, apparently with the same title, which then are published later all together. I don't know why they do that but apparently they do. 

I understand the edge case, personally I also think it's not the best way to use the system.

I will tell them that this is the way it currently works and it will not be changed in the near future. 
They'll just have to change the url when they want to publish the different drafts.

Thank you for your answer.

**Comment by GlennVL91** [comment]
Hi

I see that this is labeled as a bug. What's the current status of this bug? 
Is there any development on going or are u not planning on changing this?

Thank you for your answer.

**Comment by alexander-schranz** [comment]
@GlennVL91 I personally would not change the behaviour but we definitly should give the User feedback what error did happen the actual error message from the backend is:

> The ResouceLocator "%s" already exists at the node "%s". Please choose a different resource locator or delete the existing one before reassigning it.

**Comment by GlennVL91** [comment]
Thank u for your update, I will inform our client that this will be changed in a next update.

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed by https://github.com/sulu/sulu/pull/5799
