### ISSUE TITLE
Internal redirect does not work between pages of two webspaces

### ISSUE THREAD

**Issue by therouv** [sulu/sulu#4864]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.1
| Browser Version | Chrome Latest

#### Actual Behavior

Internal redirect to a page in another webspace results in "too many redirects" error of browser.

#### Expected Behavior

Internal redirect works.

#### Steps to Reproduce

* Create a fresh Sulu instance with 2 webspaces.
* Create a regular page in webspace A
* Create a page in webspace B and define it as an "internal redirect". Select the page in webspace A as the target.
* Assign the new pages to the main navigation.
* When you click on the link on the frontend, you'll get "too many redirects" error.

#### Possible Solutions

Possibly change [this file](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php#L150) and implement a check that if the webspace of **$document** does not equal the webspace of the redirect target **$document->getRedirectTarget()**, then change the redirect url and add the url of the webspace A.

**Comment by danrot** [comment]
There were two problems:

The first one was fixed in #4868, and basically does what you've described in your possible solution.

The other thing is that the webspace was also not considered when the URL for the navigation items. This was fixed in sulu/skeleton#20, and you have to add that line manually. As you can see in this PR the `sulu_content_path` twig function takes also the webspace as a second parameter, then it is working:

https://github.com/danrot/skeleton/blob/c208f2df9b6b4946908cd28b901967b8d253235f/templates/base.html.twig#L29-L34
