### ISSUE TITLE
Missing parameter q in Sulu\Bundle\SearchBundle\Controller\WebsiteSearchController

### ISSUE THREAD

**Issue by axzx** [sulu/sulu#4874]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.1

#### Actual Behavior

Sulu\Component\Rest\Exception\MissingParameterException:
Missing parameter q in Sulu\Bundle\SearchBundle\Controller\WebsiteSearchController

  at vendor/sulu/sulu/src/Sulu/Component/Rest/RequestParametersTrait.php:39
  at Sulu\Bundle\SearchBundle\Controller\WebsiteSearchController->getRequestParameter(object(Request), 'q', true)
     (vendor/sulu/sulu/src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php:71)
  at Sulu\Bundle\SearchBundle\Controller\WebsiteSearchController->queryAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:62)

#### Expected Behavior

Symfony profiler

#### Steps to Reproduce

http://sulu.localhost/_profiler/search?limit=10

**Comment by danrot** [comment]
I have just tested the search, and it works as expected. The only thing is that you have to pass a query parameter named `q` containing the search string (that's what the error message states).

So instead of just calling http://sulu.localhost/search you have to call something like http://sulu.localhost/search?q=Something

And a localhost link is only working on your machine, that's nothing that helps us reproduce the error.

**Comment by McAnix** [comment]
This continues to plague us in our production environment. We have email error reporting and this error is hit every time a bot touches the /search endpoint. This should just return a 400, not throw an error. Yes, we have a block in robots.txt but that is a bandaid, not a solution.
