### ISSUE TITLE
Excluded templates don't work because of missing webspace key

### ISSUE THREAD

**Issue by therouv** [sulu/sulu#4920]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.2
| Browser Version | Chrome latest

#### Actual Behavior

I want to exclude some page templates since they are not relevant for some webspaces in my Sulu instance. When I define the excluded templates in the webspace, the product types still show up.

#### Expected Behavior

The excluded page templates should not be visible to the content manager.

#### Steps to Reproduce

1. In a basic installation try to exclude the "homepage" page template or define a new page template and exclude the new template in the webspace configuration file.
2. Create a new page in the sulu admin.
3. You can still see ALL page templates.

#### Possible Solutions

Feature was introduced in #4861 

When debugging with xDebug, you can see that `$metadataOptions['webspace']` does not exist and therefore the excluded templates won't be removed from the selection.

<img width="1110" alt="xdebug" src="https://user-images.githubusercontent.com/393419/69760484-f3a06b80-1164-11ea-933b-476e85ff16ee.png">

Relevant file: 
https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php

However, it seems that the webspace key isn't already included when the react backend initializes the XHR request to retrieve the page template types. So maybe it has to be fixed in some JS file 🤔

**Comment by danrot** [comment]
Just tested, and it works as expected for me. The request sent from the react backend correctly with the `webspaceKey`.

My guess would be that you don't have the latest build of our admin. We have an [upgrade guide](http://docs.sulu.io/en/2.0/upgrades/upgrade-2.0.html) in our documentation, where step 4 describes how to get the new build. I guess you have not build anything in JS on your own (otherwise it would probably work, because you've made a build), so the easier variant is to execute the following command which downloads the latest build:

```bash
bin/console sulu:admin:download-build
```

Can you try that, and close the issue if that helps?

**Comment by therouv** [comment]
Aahhh, good to know. Thank you – it seems to work perfectly now :-)
