### ISSUE TITLE
Schema.org integration

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/sulu#4944]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2.0.2 and above
| Browser Version | any

#### Actual Behavior

Currently, there's no Schema.org integration

#### Expected Behavior

For every template the possibility to link properties the schema.org structure.

#### Possible Solutions

A node called "schema" for every template.

```
<properties>
  <property name="title" type="text_line">
    <meta>
      <title lang="en">Title</title>
    </meta>
  </property>
</properties>
<schema type="Book">
  <params name="properties" type="collection">
    <param name="name" value="title">
  </params>
</schema>
```

Where the value in a schema param refers to the property name inside properties.

After this, we could easily print a JSON-LD version of the Schema.org.

**Comment by alexander-schranz** [comment]
Schema.org is for me view specific and think this should have nothing todo with the template.xml or form.xml.

If want to build something like schema.org data out of the template structure I would recommend you using `tags` on your properties e.g.:

```xml
<properties>
  <property name="title" type="text_line">
    <meta>
      <title lang="en">Title</title>

      <tag name="schema_org.type" type="Book"/>
      <tag name="schema_org.value" value="name"/>
    </meta>
  </property>
</properties>
```

Then you can read the structure metadata and try to build it out of that.

**Comment by cirykpopeye** [comment]
@alexander-schranz I'll have a go on the above approach and will share my experience afterward. Thanks!

**Comment by danrot** [comment]
In Sulu 1.x it was necessary to have this vocabulary in order for the live preview to work, and that was also handled in the twig template. I think that is the only viable option to go, because it should not be listed in the template XML files, since this information is very output specific. There should be nothing like this if I output this data as JSON.

Therefore I am going to close this issue. Feel free to report your experience afterwards or continue to ask questions afterwards.
