### ISSUE TITLE
Drag and drop order instead of changing the sequence integer

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/sulu#4945]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 2.0.2
| Browser Version | any

#### Actual Behavior

To change the order of pages there's now the option to do so by changing the sequence ID. In our opinion, it's a bit user-unfriendly.

#### Expected Behavior

It works as it should, but it would be better if there would be a drag and drop feature to change the order. This way the user doesn't have to think about numbers.

#### Steps to Reproduce

Add a bunch of pages and try sorting them one by one, it's quite some work.

#### Possible Solutions

I would add the option for a drag and drop, though I'd keep the sequence option as that might work better for some people.

**Comment by danrot** [comment]
We have discussed that already multiple times, and until now we wanted to avoid that feature. The reasoning behind this is, that the next step would be to also allow moving pages by drag&drop (or how do you explain that this is not working if you can move them?). And that's a feature that made problems in the past with older solutions for us, because content manager tend to "lose" pages then, meaning they have no idea where they moved them, because they did that by accident.

@chirimoya Should we reconsider that decision, or does it still stand?

**Comment by cirykpopeye** [comment]
It was only intuitive that I started dragging but there was no option for it :) To avoid such comments as mentioned above I'd keep the extra step to toggle on/off sorting, so there's no confusion to why pages can't be moved because it's in "sort" mode only.

**Comment by danrot** [comment]
We will discuss that with our UX experts, and see if they can come up or approve a solution. But it has not a very high priority for us, so we will probably not implement that soon, especially because that's also quite some effort.

**Comment by danrot** [comment]
We have discussed this at length, and decided against implementing something like this.

Additionally to the already mentioned issues the reasoning behind this is, that if we introduce drag and drop for sorting, we would also have to implement it for moving pages, because that's the next thing people would expect. And implementing this for moving is even a lot harder, because if you drag something and hover another page, the children below this page should be shown (you could checkout the Mac OSX finder to better understand what I mean). We think our resources are better used for other features, than using a lot of them for implementing and maintaining(!) this feature.

It also feels that if we start going down that road, user will expect that kind of functionality in a lot of other different places, making it even a bigger burden for us.

Therefore I am going to close this issue, and I hope you understand.

Still thank you for bringing this up! :+1:
