### ISSUE TITLE
Languages for which a user has no permissions to view should not be shown

### ISSUE THREAD

**Issue by Slowwie** [sulu/sulu#5004]
# Problem description
When u have multiple languages in sulu the language can be selected in the right top corner even when u have no permission to do something within it. 

So when u wanna edit a page content - the Sulu-admin-UI loads infinitely. No error "U have no permissions to edit this page in this language."

The user / developer can find out whats the problem only if they check the ajax responses. 

# Proposed solution
Don't show languages wich a user has no permission to edit it at all. So the problem would be solved.

**Comment by danrot** [comment]
I've adjusted the title a bit, because the user should still be able to see the content of the page, if they have the `view` permission.

I would also say that we have to fix two things here: 

1. Do not show the languages for which the user has no `view` permissions, as you have already proposed.
2. Show a no permission icon or something similar if a form is opened for which the user has no permission. While it is not possible to reach this state via the UI if we implement point 1, it is still possible to get there via clicking on a direct link from e.g. a chat message.

**Comment by danrot** [comment]
I have just realized that there is already #2300, which is exactly describing the same issue. Therefore I am going to close this one as duplicate. Please feel free to subscribe to #2300 in order to get updated once we have fixed this issue (we are planning to at least implement the second point quite soon).
