### ISSUE TITLE
Preview problems

### ISSUE THREAD

**Issue by eekes** [sulu/sulu#5019]
In the admin, when I'm clicking "Open in a new window", the iframe has disappeared. Then when clicking through the first 4 tabs (Details, SEO, Excerpt & Taxonomies, Settings) it stays hidden. When I click "Permissions", and then go back to one of the other 4 tabs, the iframe reappears again.

Also, every URL in the preview contains {host} instead of the real hostname.

BTW, great job! Been working with Sulu for some days now and I just love it! 😄

**Comment by danrot** [comment]
Thank you for the kind words :blush: 

But can I ask you to create two separate issues for that? Because they are not really connected. So you would have:

1. The `{host}` part is not correctly replaced in the preview
2. The preview iframe appears again after switching back from the Permissions tab although it is already opened in a separate window

And it would be nice if you could fill the information from the issue template, instead of just deleting it :slightly_smiling_face:

**Comment by eekes** [comment]
@danrot sorry will do it now, I'm pretty new to the whole open-source contributing thing 😄

**Comment by danrot** [comment]
No worries, thank you for your effort :smiley: But if we keep issues to a single problem, it is easier for us to handle them, and we can close them faster, instead of waiting for everything mentioned in the issue being fixed :slightly_smiling_face: Gives you faster feedback as well.
