### ISSUE TITLE
[MediaBundle] Use always League Filesystem for storage

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5120]
| Q | A
| --- | ---
| Sulu Version | 2.0.4
| Browser Version | All

# Actual Behavior

FormatManager is using LocalFormatCache which is implemented with Symfony Filesystem

# Expected Behavior

Use always configured storage

# Steps to Reproduce

Configure Google Cloud or S3 and check format_path in local . Images are created there.

# Possible Solutions

LocalFormatCache ( rename to FormatCache maybe ) must use the configured League Filesystem.
We should change the file system to always use "League" even for local

I have override "sulu_media.format_cache" with Filesystem and it's not difficult to implement with League Filesystem. 

I can try to do it if you thing it's a good strategy or maybe do you think that must create a service for each storage?

**Comment by alexander-schranz** [comment]
Thank you for creating this issue but think this is for me more a feature request then a bug as it is currently designed this way to be.

I want first explain how the image formats are generated to give you an overview about the current process. 

The very important thing is that the image format is generated on first request of the image format not when you upload a media, so in all cases its necessary to call the controller which generates the image.

The detail procedure is the following:

![Image Handling](https://raw.githubusercontent.com/sulu/docs/master/detail-specification/images/diagrams/ImageProxy.png)

So in the vhost of sulu you see that it first look if the file exist and only when it does not exist then call the controller. If the image format is generated the format cache will save it to the folder where the webserver does look for it and so PHP is not called again for this formats. So **loading from cache**  is never done by PHP so it don't make sense to save the image external.

If you are in **cloud setup** you disable normally the format cache this way as you don't want to save images locally:

```
sulu_media
     format_cache: # locale format cache would maybe be a better name here
          save_image: true
```

Instead you have a `reverse proxy` in front of your `/uploads/media` mostly by using example a nginx cache or a reverse proxy cdn like [fastly](https://www.fastly.com/). 

So in the cloud scenerio the reverse proxy first look if it has the image if not it need to call the sulu controller to generate the image, sulu will generate the image but will not save the thumb locally as it is not needed in this kind of setup. The reverse proxy gets the image and will cache it for future requests.

I hope you now have a basic overview how it currently works in a standard setup and a cloud setup.

So as when not caching the files locally there need to be somebody in front caching and loading it from cache and when the file is not in cache calling the sulu controller. How do you currently did setup that `/uploads/media` are loaded directly from cache and fallback to the controller. And why can't this service not just use the response to create the cached file, does your service redirect instead of work as reverse proxy between?

**Comment by plozmun** [comment]
Hi @alexander-schranz , I think it's a feature too.

I understood how cache works but I think that the performance could be improved by saving the images generated, especially the thumbnails.

I have varnish as a reverse proxy and if a page has many images when the cache expires the loading time increases. That's why I think it's better to save it to disk (even if you also cache it with a reverse proxy). 

But local caching has the problem that in a cloud systems with multiple pods the disk is not shared. That's why my suggestion is to save it in the cloud storage itself.

**Comment by alexander-schranz** [comment]
@plozmun but the files are never loaded over PHP from cache, so saving to an external storage will have no effect the image will always bei regenerated if your reverse proxy doesnt handle caching for it. Have generated thumbnails in remote storages leak also in performance, you should definitely avoid that PHP is called for generated images. We use own nginx proxy which just handles caching maybe @wachterjohannes can provider more information about the reverse proxy Setup for Images in our kubernetes deployments, you should not use the same cache you use you for pages as that will be purged sometimes.
We also have Projects with simple deploy in 2 webservers and also there I would not use a shared drive or external storage for generated images, just let it generated in both server so you can provider the image as fast as possible to the clients and not from a slower external drive. Aslong as PHP doesn't care about the local cache I see not why it should store it external. But thats my personal opinion on this, maybe the others team members has there own view on this topic.

**Comment by plozmun** [comment]
I have a site with 5 pods with 2K images more or less. If you have to deploy all the stack twice a week and generate thumbnails again the performance is worst i think.
If you stores that thumbs in cloud, each server only have to check if exists and return to reverse proxy for caching.

**Comment by plozmun** [comment]
And maybe to avoid slow IO lookups on cloud use League Filesystem cache system. eZPlatform for example uses DFS for this case

**Comment by alexander-schranz** [comment]
At current state you should setup a reverse proxy like the following:

```nginx
proxy_cache_path /var/nginx/cache levels=1:2 keys_zone=my_cache:16m max_size=16g inactive=180d use_temp_path=off;

server {
    root /usr/share/nginx/html;

    location / {
        index index.html;
    }

    location /uploads/media {
        proxy_cache my_cache;
{{- if .Values.mediaproxy.authentication -}}
        proxy_set_header Authorization "Basic {{ .Values.mediaproxy.authentication|b64enc }}";
{{- end }}
        proxy_pass {{ include "mediaproxy.backend_uri" . }};
        proxy_ignore_headers "Set-Cookie";
        proxy_ignore_headers Cache-Control;
        proxy_cache_valid 200 180d;

        add_header X-Cache-Status $upstream_cache_status;
   }
}
```

and then mount a persisted value for the cache folder so it don't get lost between your deploys:

```yaml
                volumeMounts:
                  - mountPath: /var/nginx/cache
                    name: mediaproxy-data
```

**Comment by plozmun** [comment]
Ok! I'll try it. Thank you

**Comment by danrot** [comment]
I think @alexander-schranz has explained pretty well why the `FormatManager` should not handle images in cloud services, and this behavior can be deactivated. Therefore I am going to close this issue.
