### ISSUE TITLE
(semi)Automatic update of URL when changing page title

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/sulu#5229]
# Problem description

When changing the title of a page the URL does not change accordingly, to update the URL now you'd actually have to type it in manually which creates a usability problem. 

# Proposed solution

Automatic: Update the URL according to the title when it's changed, so with an eventlistener on input.
Semi-automatic: Update the URL using a "refresh" button, on click of the button a new URL will be generated for that page.

What do you think about this feature, and would you opt for automatic/semi-automatic?

**Comment by nnatter** [comment]
Regenerating the URL every time the title is adjusted might lead to a lot of blocked URLs because old URLs are still present i the URL history of the page. So I would prefer a `regenerate` button. That shouldnt be that hard to implement too 🙂 

Also, we could probably close the following related issues as this will not be implmented in 1.6: https://github.com/sulu/sulu/issues/4221 https://github.com/sulu/sulu/issues/2452

**Comment by danrot** [comment]
#4221 has already been attached to the 2.0 release, so I am going to close this one instead (this has already been discussed and we we want to introduce a refresh button as described in #4221 already.
