### ISSUE TITLE
Sort page templates alphabetically in current language

### ISSUE THREAD

**Issue by man-andy** [sulu/sulu#5288]
# Problem description

Currently the page templates are sorted by the order in the xml template, instead I think it would be great if the dropdown is sorted alphabetically by the users language for better user experience.

Related Issue:sulu/sulu/issues/5086

# Proposed solution

A. Sort block types alphabetically in current language by default

B. Make sorting of block types configureable e.g.: `<types sort-by="title">`

**Comment by danrot** [comment]
Just to clarify this: Your proposed solution does not really affect what you are describing here, does it? I think currently the page templates are sorted by their keys, and since every template has its own file, which does not know anything about the others, there is no way to configure this via some XML configuration.

The way I see it, we would have to change the default sorting. I think I would support that,
because sorting them by key does not really make sense. The only disadvantage I can think about, is that the positioning of these elements is different for every language then, so if two people would be talking about the "first template" they could mean something different. But I don't think that this would be really a problem.

@sulu/core-team Does anything speak against sorting the page templates by the localized title? If not, I would quickly implement this.

**Comment by nnatter** [comment]
Sorting by title instead of key sounds sensible to me. If somebody wants to have the same order for all languages, he could still make things explicit and prefix the title with numbers for his desired order.

Not sure how webspaces are sorted at the moment, but we should probably implement the same sorting there.

**Comment by danrot** [comment]
@man-andy Thanks for raising the issue! This will be fixed in Sulu 2.2.
