### ISSUE TITLE
Resource Locator doesn't update when parent change

### ISSUE THREAD

**Issue by plozmun** [sulu/sulu#5302]
| Q | A
| --- | ---
| Sulu Version | 2.0.6 to 2.1RC1
| Browser Version | -

# Actual Behavior

When a page slug is changed , url is not updated to all children

# Expected Behavior

Slug must change in all children

# Steps to Reproduce

- Go to sulu.rocks
- Change artists slug to artists2 
- Go to /artists2 url and check children slugs.  Urls are not updated and sometimes response old and new url : Ex: https://sulu.rocks/en/artists/coyoos https://sulu.rocks/en/artists2/coyoos get 200 on both

**Comment by alexander-schranz** [comment]
@plozmun The problem here is not that the url is not updated correctly to the child. The problem here is that when you publish the parent page ONLY the parent page will be published. So currently the new URL for the child is only available if you also republish the child page else it will stay the old way.

So basically on the Publish Event we also need to update the childs urls.

**Comment by alexander-schranz** [comment]
Think this is related to #4990

**Comment by plozmun** [comment]
Yes, it's the same issue. I have fixed publishing all children again. Close this issue then?

**Comment by alexander-schranz** [comment]
Yeah I added my thoughts also there so I will close this one.

**Comment by alexander-schranz** [comment]
@plozmun Still thank you for report this issue.
