### ISSUE TITLE
Page type "folder" and icons in webspaces

### ISSUE THREAD

**Issue by mavimedia** [sulu/sulu#5310]
# Problem description
The Webspace functionality is very powerfull with the ability to use page templates. So one can create a lot of different pages with different content structure.
But it is not clear on structuring the pages. All pages seem same on the Webspaces view.

# Proposed solution
It would be nice to have a page type "folder" for structuring the pages like in TYPO3.
It would also be great, if the page types have different icons, wich are shown on webspaces view.
This would help structuring the pages and make the webspace a little bit clearer.

**Comment by danrot** [comment]
First of all, thanks for your feature request!

This issue already came up in the past in #4356, and I have [listed a few reasons why we are not implementing this](https://github.com/sulu/sulu/issues/4356#issuecomment-573632131).

Especially since this structure should also represent the structure of the website, we feel it would be too confusing to introduce features that would break this principle.

Therefore I am going to close this issue.
