### ISSUE TITLE
Uploaded images are not cacheable

### ISSUE THREAD

**Issue by tvwijgerden** [sulu/sulu#5355]
# Problem description

Images that are uploaded using the FlysystemStorage don't have a Cache-Control header set, which makes the images not cacheable.

# Proposed solution

Add a configuration option to the MediaBundle in which a Cache-Control header can be configured for different mime types, which the FlysystemStorage adds to the file when uploading it.

**Comment by alexander-schranz** [comment]
@tvwijgerden I think you are misusing the `.url` attribute on the media. The `.url` should only used as a link to download a media, never used to embed a image on the website. If you want to embed an image on the website it should be done by greating a [image format](https://docs.sulu.io/en/2.0/book/image-formats.html). This files are then directly stored in the public folder and cached for the time you configure in your [vhost](https://docs.sulu.io/en/latest/cookbook/web-server/nginx.html).

**Comment by tvwijgerden** [comment]
@alexander-schranz We use CloudImage to get our image formats. So the base image that is uploaded to the objectstore is used by CloudImage to generate the image formats. Because the image on the object store isn't cacheable CloudImage will always make a call to the object store which is not efficient.

**Comment by alexander-schranz** [comment]
@tvwijgerden I don't think sulu can do here anything if you use a external storage it will be downloaded from the external url and so its not a response from sulu so sulu can not set the response headers. Maybe google cloud, azure or whatever storage you use allow to set response headers in there configuration.

In your case I would contact CloudImage and check if they could provide a min cache time setting in there proxy configuration.

If that doesn't work In your case I would create a image format with a big width attribute:

```xml
    <format key="original">
        <meta>
            <title lang="en">Original</title>
            <title lang="de">Original</title>
        </meta>

        <scale x="9999"/>
    </format>
```

Sulu will not upscale images so you will just get the original sized image and so you can configure the response header on your server. And then you can use this image instead of the .url attribute.

**Comment by tvwijgerden** [comment]
@alexander-schranz I think you're misunderstanding the issue. The current code in Sulu when uploading the image using the FilesystemStorage is the following:
```
$this->filesystem->writeStream(
    $filePath,
    fopen($tempPath, 'r'),
    ['visibility' => AdapterInterface::VISIBILITY_PUBLIC]
);
```

The following change to the code above would fix the issue we're having:
```
$this->filesystem->writeStream(
    $filePath,
    fopen($tempPath, 'r'),
    [
        'visibility' => AdapterInterface::VISIBILITY_PUBLIC,
        'Cache-Control' => 'max-age=2628000, public''
    ]
);
```

When adding the Cache-Control key to the config array of the `writeStream` method, the objectstore will add the key with the value to the metadata of the file. The image shows an example of how this looks for an image on a AWS S3 bucket. 

![image](https://user-images.githubusercontent.com/16238219/85045066-c5c95580-b18e-11ea-8198-baad8806dc9b.png)

When this Cache-Control metadata is set and the image is requested from the objectstore, it will return the Cache-Control header in the response headers and the image will be cacheable. And that's what we're after.

**Comment by alexander-schranz** [comment]
@tvwijgerden Oh I see, didn't know there is an option for it on upload. Not sure where we should configure it then. Could think about something like:

```yaml
sulu_media:
    download:
        cache_control: 'max-age=2628000, public' # default to null and so not set for BC
```

So this configured value could also be used for the LocalStorage in the MediaStreamController on the BinaryFileResponse.

/cc @sulu/core-team what do you think about this?

**Comment by danrot** [comment]
Wondering if we should not rather include that somehow in the adapter configuration. Would be a clearer separation IMO (also for the current use case it would rather be `upload` than `download`, wouldn't it?).

Also, if we use that also for the `MediaStreamController`, it might break the [download counter feature](https://github.com/sulu/sulu/blob/7fc5cac/src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php#L142), since downloading has a side effect, it cannot really be cached, unless we get rid of that feature.

**Comment by tvwijgerden** [comment]
@danrot I agree that adding it to the adapter configuration would be better. And yes, the use case is just for `upload`.

**Comment by alexander-schranz** [comment]
I personally think the LocalAdapter should behave the same way as the external adapters that why I would not introduce a adapter specific configuration and as it effects how the media is downloaded I would configure it there that it is set on upload to the external storage is for me just a implementation detail on our side as I did see that its also possible to set the cache control also when the url is generated when calling the media stream controller, which would from my side make more sense when we go in direction private media security.

About the download counter, I think that is something I would then just document that it could have an effect on that, by default I would definitely not set a cache control also from backward compatibility view.

**Comment by danrot** [comment]
If this metadata passed here are really only HTTP headers that will be added when the file is requested I am fine with that. In case it could be more (don't know what these services are doing with this metadata) I think that might be confusing.

**Comment by tvwijgerden** [comment]
The metadata that is passed here only adds the HTTP headers when the file is requested. I think the easiest solution here is to add the configuration to the adapter. I don't see how modifying anything related to downloads within Sulu has anything to do with this feature. Because I think adding metadata to the uploaded file won't have any effect to anything download related within Sulu.

**Comment by alexander-schranz** [comment]
I don't think its a good idea to have for every adapter s3, azure, google cloud, minio, ... a seperate configuration option.

Then somebody request why he can't set cache headers for local storage and why its different between when using the local or external adapter in different environments. As said I think we should definitely not go with adapter specific configuration all adapters should behave the same and end in the same result. If somebody want todo something adapter specific he probably should then go more with decorating that adapter then having adapter specific configurations.

**Comment by danrot** [comment]
When reading this again, I think we are mixing up a few things here...

How should the metadata we are talking about here be added to the local storage at all? Should the `MediaStreamController::downloadAction` at all be affected by this? The way I understand @tvwijgerden it should not, so what he is proposing here, cannot even be applied to the `local` storage, if I understand that correctly. 

@tvwijgerden Why exactly do you want that information on the host? In order to download these document/images also in a non-sulu context?

**Comment by tvwijgerden** [comment]
@danrot What you are saying is correct. It cannot be applied to the local storage because there is no way to provide extra metadata to it. 

We want the extra metadata in AWS to make sure the images are cacheable when requested (from a non-sulu context). The only thing that falls within the Sulu context in this feature request is adding the metadata when uploading the file.

**Comment by alexander-schranz** [comment]
@danrot What we want is to add possibility to add Cache-Control headers to downloaded media and thats possible for Local Storage (setting the http header in our controller) and External Storage (setting metadata or add it to the url generation of the external service).

**Comment by danrot** [comment]
Had a closer look at the code, and I think what I was missing, is that our Controller makes a redirect to the cloud URL, is that correct? Then we could implement it like you suggested. Still not sure if the configuration you suggested is completely clear on this... If I change that configuration later on, it would not affect the URLs being returned from the cloud, right? That might be a bit confusing... But maybe it also does not matter in practice.

**Comment by nnatter** [comment]
Is this already solved? 🤔
