### ISSUE TITLE
Cache (fos_http_cache) completely deactivated when security is activated

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#5480]
| Q | A
| --- | ---
| Sulu Version | dev-master
| Browser Version | all

# Actual Behavior

Currently the NavigationTwigExtension uses the user to determine the current role of the user.

Therefor on all pages which uses a navigation has a session.

When a session is startet symfony's `AbstractSessionListener` set all responses to private.

# Expected Behavior

The responses should not be private only when i use a Navigation.

# Steps to Reproduce

Install sulu-skeleton and call a navigation twig extension.

# Possible Solutions

No idea

**Comment by alexander-schranz** [comment]
**Solution A**

Currently I think I we would need to introduce a new configuration to enable this:

```yaml
sulu_security:
    website_security: true
```

Else it could break exist website which use the community bundle as they will be uncacheable when updating to the master branch.

**Solution B**

We detect if the fos_http_cache bundle has user_context based caching active end then set the `sulu_security.website_security` parameter to `true`:

```yaml
fos_http_cache:
    user_context:
        enabled: true
```

--------

In both solutions we need to check in the service for the parameter. As a solution we could also create a `sulu_security.website_token_storage` service alias and only create that service alias when enabled use:

```xml
<argument type="service" id="sulu_security.website_token_storage" on-invalid="null"/>
```

Where we currently use the `token_storage` service of symfony.

Open questions is for me should it be possible to enable the security check per `system` then we would need to go with something like:

```yaml
sulu_security:
    website_security:
          checkin: true
          other: true
```

**Comment by danrot** [comment]
I see a third solution I would favor over introducing more configuration than we already have:

Why don't we only load the user if the webspace has a system configured? That would somehow also solve the last question you've asked, without the need to defining stuff multiple times in different places. If I don't want to have security enabled I simply don't set a `security` tag in the webspace configuration, which would totally make sense to me. And I don't see a use case where somebody wants to set the security tag but not having any security checks on the website.

**Comment by alexander-schranz** [comment]
@danrot the problem is we are talking about websites which have a security system configured in there webspace as they use the sulu community bundle and have a firewall configured for the website. So we can not go on the webspace configuration. We need to add a additional configuration option or detect if user_context is enabled is enabled.

**Comment by danrot** [comment]
As soon as they have security system configured, the content manager has the possibility to exclude certain pages, and therefore we need to do that check anyway.

That being said, I've had a similar issue where I consulted somebody, that also led to the cache not working as expected, because that person had a form with a CSRF protection on every page, which also stores the key in the session, leading to the same bug, so it is not only about the stuff we've added in the `master` branch.

I start to think that this new functionality of Symfony causes more troubles than it solves, and would at least consider to [deactivate it using the `NO_AUTO_CACHE_CONTROL_HEADER`](https://symfony.com/doc/current/http_cache.html#http-caching-and-user-sessions).

**Comment by danrot** [comment]
We have discussed that issue further, and came to the conclusion that we would like to add a new configuration, but within the webspace XML configuration file, to avoid touching multiple files at once for configuring a single feature. This is because some websites want our permissions to be automatically checked, while others only need the security system to setup a firewall in Symfony, and want to protect the entire webspace.

Therefore we have to think about how to name and where to place this attribute. When we were talking about this, we said that we want to start our security in different modes or different levels. Alternatively we could also say that only the checking of permissions is different. So I would suggest the following for the naming of this attribute:

1. **check** as a boolean
2. **mode** with the values `off`, `set` (to only set the system in the `SystemStore` and let the developer decide to handle it) and `check`

The next question would be how to place that configuration in the XML file. Could think about the following solutions (assuming the `check` variant, same thoughts can be applied for `mode`):

```xml
<security check="true">
    <system>website</system>
</security>
```

```xml
<security>
    <system check="true">website</system>
</security>
```

```xml
<security>
    <system>website</system>
    <check>true</check>
</security>
```

Or do we want to make that configuration even more fine-grained? Then I could imagine stuff like this:

```xml
<security>
    <system>website</system>
    <check navigation="true" smart-content="false" />
</security>
```

**Comment by nnatter** [comment]
I feel like enabling the security for the `navigation` but not for the `smart_content` is not a common usecase. Alos it makes the configuration mor complicated, so I dont think I would implement a fine-grained control. But I dont know a lot about the feature to be honest 😇 

I think I would go with a `mode`. Not sure if we should use a `<mode>` tag or a `mode` attribute and use snake-case or kebab-case 🙈 

```
<security>
    <system>website</system>
    <mode>detect-system / check-permissions</check>
</security>
```
```
<security mode="detect-system / check-permissions">
    <system>website</system>
</security>
```

**Comment by danrot** [comment]
Yeah, I also think that more fine-grained control is not really necessary... Would just be a reason to go with a separate tag, because then we can add as many attributes as we want.

And I am not completely sure if it is clear from just reading these values that `check-permissions` somehow includes `detect-system`, and it is not something completely different. But maybe that needs to be explained anyway, since I also don't have any better idea :see_no_evil:

**Comment by danrot** [comment]
In a short call with @chirimoya and @alexander-schranz we decided to use that configuration:

```xml
<security permission-check="true">
    <system>website</system>
</security>
```

**Comment by danrot** [comment]
In #5439 a lot of functions like the following were introduced:

https://github.com/sulu/sulu/blob/aaa1273abefcd3016243766b0199729097dd074b/src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/NavigationTwigExtension.php#L207-L225

They all have more or less the same content, and it probably was already questionable back then to decide to duplicate that. But since this is part of the Symfony API, one could argue that there must be a reason they haven't made that easier.

Now that we are adding even more information in these functions (we have to check if the webspace we are checking the permissions for has the `permission-check` flag set to `true` by calling the `Webspace::hasWebsiteSecurity` flag) there would probably be too much code duplicated, if we do not extract that into a separate service.

Maybe we can keep some of the Symfony jargon and name that new service something like `WebspaceTokenStorage`. I would still add a `getUser` method to that service, that would allow us to do what is being currently implemented in the code above. Alternatively we could name it `WebspaceUserStorage` instead, because it never returns a `Token` instance. (Found an interesting [closed PR in Symfony](https://github.com/symfony/symfony/pull/25617) in that regard).

I have also seen that there is a [`Security` class in Symfony that does exactly what we are doing in every place](https://github.com/symfony/symfony/blob/6987862d97166c6d2f9882285eca93b03ffc7b5e/src/Symfony/Component/Security/Core/Security.php#L38-L54). So by using that service we would have less code in our own codebase. It might even make the `WebspaceUserStorage` service obsolete (or at least a bit easier to implement), because we could just use that `Security` service in many places, and only have to put that call around an `if`, which checks if the webspace has website security.

A question that is still open in order to answer that with certainty is how the flag we have decided on in my previous comment affects other webspaces. Imagine we have a link from webspace A (without permission check) to webspace B (with permission check). Should the permissions for this link be checked now?

1. If the permission should not be checked, we could reuse the exact same logic to load the user, because we can always rely on the currently active webspace to check for that flag. Then a separate `WebspaceUserStorage` would definitely make sense, because calling it would always look something like that:

```php
$webspaceUserStorage->getUser();
```

2. If the permissions should be checked, because the other page is within a webspace that requires a permission check it is not so clear anymore. In my opinion we have two options then:

    1. One solution would be to pass the key of the webspace for which we want to load the user to the `getUser` method above, and if it is omitted we use the current webspace key.

    ```php
    $webspaceUserStorage->getUser($optionalWebspaceKey);
    ```

    2. We don't have to define that new service at all, and instead of having the multiple lines for each `getUser` function we have currently defined we can use the `security` service that comes with Symfony and only put a single if around it:

    ```php
    public function getUser() {
        if ($webspace->hasWebsiteSecurity()) {
            return $security->getUser();
        }

        return null;
    }
    ```

Option 2ii) might be more explicit when reading the code, while still being shorter than what we currently have. But it requires everybody trying to load a user to implement that (although it is not a lot) and to inject services like the `WebspaceManager` and/or `RequestAnalyzer`. For this reason I would say we should definitely define a `WebspaceUserStorage` service or something like this, because it makes the live for the developer considerable easier.

I also think that we don't need the `$webspaceKey` in the `WebspaceUserStorage::getUser` function, because if the `permission-check` is set to false, people probably assume that Sulu never starts a session for this webspace (that's actually the reason we are doing this). If we choose to do otherwise, a session might still be started, even if webspace A has the `permission-check` flag set to false.

What do you think?

**Comment by danrot** [comment]
In a short call with @chirimoya and @alexander-schranz we have decided that the `WebspaceUserStorage` service is probably not necessary. Instead we will make a check based on the current webspace, which we can e.g. get from the `RequestAnalyzer`, and only execute the security check in our code if the webspace has the flag activated.

Instead of the all the `getUser` function spread around in our code we are trying to use the `security` service of Symfony.
