### ISSUE TITLE
Anonymous role "IS_ANONYMOUS" Does not exist in AuthenticatedVoter in symfony 4.

### ISSUE THREAD

**Issue by C-burr** [sulu/sulu#5483]
dev-master#96096d163f29679215845f3877fa67da33f377ef

# Actual Behavior

When saving the permissions of media collections (or other things), an error occurs at:
sulu/sulu/src/Sulu/Bundle/SecurityBundle/Entity/Role.php Line 120

`AuthenticatedVoter::IS_ANONYMOUS ` does not exist in Symfony 4, only in Symfony 5.
Instead i think it should be something like this: `AuthenticatedVoter::IS_AUTHENTICATED_ANONYMOUSLY`

# Expected Behavior

I should be able to save permissions.

# Steps to Reproduce

When saving the permissions of media collections.
![Bildschirmfoto 2020-09-03 um 11 45 17](https://user-images.githubusercontent.com/30287946/92115791-43e2e300-edf3-11ea-9032-ff4f009b93b9.png)

# Possible Solution
Create a fallback value for Symfony 4 systems.

**Comment by alexander-schranz** [comment]
I used that constant as it represents how currently the Anonymous Role is Implemented. As it only effects ANONYMOUS Users and has no effect on logged in users which `IS_AUTHENTICATED_ANONYMOUSLY` would represent. See description in the [symfony docs](https://symfony.com/doc/5.1/security.html#checking-to-see-if-a-user-is-logged-in-is-authenticated-fully). So using `IS_AUTHENTICATED_ANONYMOUSLY` I would avoid. 

Currently I see the following solutions:

**Solution A**

Use `"IS_ANONYMOUS"` as string or fallback to this string if constant does not exist

**Solution B**

Use own constant which does nothing have todo with symfony e.g.: `ANONYMOUS`.

**Comment by danrot** [comment]
@alexander-schranz I've had just a look at the Symfony code, and the use of a role named `IS_ANONYMOUS` has an impact from what I can see (otherwise it would have been strange if they've introduced a constant). 

The following part was missing in older Symfony versions, so an update of a minor Symfony version might cause the Voter to return granted instead of abstain, which might lead to a security leak:

https://github.com/symfony/symfony/blob/80e5a7fbd80ef04fced05bb3d4bcb8816fa897be/src/Symfony/Component/Security/Core/Authorization/Voter/AuthenticatedVoter.php#L88-L90

Either we accept that BC break and document it very well in our `UPGRADE.md`, or we use a different name. Would say something like `IS_SULU_ANONYMOUS` would make sense. I think I would tend to the latter solution, since people probably won't read our `UPGRADE.md` file if they only update Symfony.

**Comment by alexander-schranz** [comment]
@danrot using `IS_SULU_ANONYMOUS` is okay for me. The above voter still is never called with an AnonymousRole of Sulu as you can not assign AnonymousRole to Sulu Users.
