### ISSUE TITLE
"Single_page_selection" in default snippet returns null

### ISSUE THREAD

**Issue by Skullfox** [sulu/sulu#5530]
| Q | A
| --- | ---
| Sulu Version | dev-master#79dc09a818f36928721644225ba587ec82ba9d7e
| Browser Version | -

# Actual Behavior

`single_page_selection` used in a default-snippet returns `null`.

# Expected Behavior

Should return `UUID`.

# Steps to Reproduce

Add `single_page_selection` to snippet/xml and select it as any default-snippet.

@danrot

**Comment by danrot** [comment]
This is a combination of two different problems:

1. [This line doing the security check](https://github.com/sulu/sulu/blob/20a3f69edef39b15cd28ed685d0fde2e652ab968/src/Sulu/Bundle/PageBundle/Content/Types/SinglePageSelection.php#L89) uses the `webspace` of the current page for that. Since the target page could be located in another webspace, we would probably have to check for the permissions in that webspace. The only problem is, that currently this page is not loaded and there is only a UUID available. So if we would like to implement that, we would have to load the document based on the UUID, so that we can tell from which webspace the document has been loaded.
2. The other problem is, that if the SinglePageSelection is in a snippet, it tries to load the webspace from the snippet, which does not have one, and because of the way it is implemented it will return `snippets`. This webspace probably does not exist, so this return value is not correct. I think it should either return `null` or the name of the current webspace. This would probably also solve the issue in @Skullfox usecase, but would not be a general solution, since it would still fail to correctly check the permissions if the targeted page is form another webspace.

**Comment by danrot** [comment]
If we are going to fix my first mentioned point (which would make sense IMO), then it would probably also make sense to fix also #545 at the same time. Otherwise we would load the page just for the security check, and would load it again when twig renders the page, because there is no other way to retrieve the data in the twig template.

We could do this by introducing a flag as described in the [other issue's comment](https://github.com/sulu/sulu/issues/545#issuecomment-579823268).

**Comment by alexander-schranz** [comment]
Maybe we should avoid at current state avoid to permission check and only make sure that 
e.g. `sulu_content_load` returns only a page which I have permissions for?

**Comment by danrot** [comment]
The problem with that approach is that we might have to deal with that in multiple places (e.g. the `<sulu-link>` tag also comes to mind). It would also be easy to overlook it in certain situations... But yeah, it still is a viable option we can think about.

**Comment by danrot** [comment]
Just had a call with @chirimoya about this topic. We decided that we have to check the permissions in `sulu_content_load` and the `sulu-link` tag anyway, because these functions could also be called with a hard coded UUID (e.g. located in the config). So we are implementing it for these functions for now, and always return the UUID in the Content Type. We also think that this might be the better decision, because who knows how soon we might start replacing the content types anway.
