### ISSUE TITLE
External Link for subdomain is not working

### ISSUE THREAD

**Issue by rogoit** [sulu/sulu#5624]
| Q | A
| --- | ---
| Sulu Version | 2.1.1
| Browser Version | Chrome 84.0.4147.105

# Actual Behavior

How does Sulu behave at the moment? 
The external link try to open a lokal page and go to 404

# Expected Behavior

What is the behavior you expect?
Open link to external URL, would be also cool when you could select target blank

# Steps to Reproduce
https://nevercodealone.de/blog-magazin
https://github.com/nevercodealone/cms-symfony-sulu

![Bildschirmfoto von 2020-11-12 13-16-05](https://user-images.githubusercontent.com/3101439/98939431-b950eb00-24e9-11eb-80a9-3b3ae4c4465e.png)
![Bildschirmfoto von 2020-11-12 13-15-47](https://user-images.githubusercontent.com/3101439/98939432-b9e98180-24e9-11eb-84ff-da449afb10cd.png)

**Comment by alexander-schranz** [comment]
You are accessing the `phpcr.path` instead of the url you should use here https://github.com/nevercodealone/cms-symfony-sulu/blob/a447341aa7f5afa882fcf7575e1e483366da5e52/templates/base.html.twig#L95, also its important to use the `sulu_content_path` this will apply your webspace url settings to the url.

So:

```twig
{{ sulu_content_path(item.url) }}
```

Same for child see:

```twig
{{ sulu_content_path(child.url) }}
```

See also:

 - https://sulu.io/blog/how-to-use-sulu-s-navigation-contexts
 - https://github.com/sulu/sulu-demo/blob/master/templates/includes/navbar.html.twig#L12

**Comment by rogoit** [comment]
Thx for the clearing and your time on this noob issue ;)
