### ISSUE TITLE
Unselecting segements is not working.

### ISSUE THREAD

**Issue by Quehnie** [sulu/sulu#5653]
| Q | A
| --- | ---
| Sulu Version | 3f2225e3defcc8cfc218380c2e65d65b1084bf31

# Actual Behavior

When a segment is selected and saved,
the unselection "None selected" does not overwrite the saved content.

# Expected Behavior

there is no more selected segment in the excerpt.

# Steps to Reproduce

Add segments, save a page with segment and try to unselect this segment.

**Comment by Quehnie** [comment]
Property is removed in "draft" but not removed in "published" document

**Comment by chirimoya** [comment]
@danrot please have a look.

**Comment by danrot** [comment]
At first I thought this are two separate issues:

1. Why does it load published data although it should not?
2. Why is removing the value not applied in the live workspace as well?

But as it turns out point 1 is not really an issue, it is just a follow-up on point 2. Recognized that, because when only saving the excerpt as a draft, the value is not set back to its previous value (so for the draft workspace everything seems to work as expected) and even if the excerpt is published with no segment being selected, the correct value will be shown after a reload of the current page.

So I am trying to find out why the change is only applied in the draft workspace, this should fix both issues.

**Comment by alexander-schranz** [comment]
@danrot when unselecting the segment property is removed from the draft workspace. But publishing will just write all properties from draft to live. So there is the issue as the property does not exist it will not be overwritten or removed. So there are 2 solutions, add a listener which will also remove on publish the not set webspaces or write null instead of remove the property from the draft workspace so publish will also set it to null on the publishing process.

**Comment by danrot** [comment]
@alexander-schranz Already realized that problem, and that it does not seem to be unique to segments. Guess we have to go over all properties on publish, and remove the ones that do not exist in the draft workspace anymore. Otherwise we are going to experience the same problem in other situations as well (guess it already is the same for the `single_select`). Writing `null` to a property is not an option, because PHPCR handles that in the same way as removing a property.

**Comment by danrot** [comment]
Fixed in #5657
