### ISSUE TITLE
Can't paginate on media selection

### ISSUE THREAD

**Issue by binarious** [sulu/sulu#5668]
| Q | A
| --- | ---
| Sulu Version | 2.2.2
| Browser Version | Brave 1.17.73 (Chromium: 87.0.4280.67)

# Actual Behavior

The pagination shows multiple pages, but the arrows are disabled.

# Expected Behavior

The arrows should not be disabled and the pagination should work.

# Steps to Reproduce

- Have enough media to cause multiple pages
- Use a media selection type and open the media selection

![image](https://user-images.githubusercontent.com/200375/100523950-875faa00-31b4-11eb-8eb5-5363b91fcfd3.png)

**Comment by nnatter** [comment]
I think this should already be fixed by https://github.com/sulu/sulu/pull/5584 which was included in `2.1.6` and `2.2.2`. 

Is it possible that you have not updated the build of the administration interface when upgrading you application?
You can do that by using the `bin/console sulu:admin:update-build` command:
https://docs.sulu.io/en/2.2/upgrades/upgrade-2.x.html

**Comment by binarious** [comment]
You're right, it works after updating the build - thanks. Sorry to have bothered you.

**Comment by nnatter** [comment]
No problem 🙂
