### ISSUE TITLE
Sulu repositories using / not using github actions

### ISSUE THREAD

**Issue by luca-rath** [sulu/sulu#5693]
These are the most important repositories, which need to be migrated from travis to github actions.

# Sulu

- [x] https://github.com/sulu/sulu
- [x] https://github.com/sulu/skeleton
- [x] https://github.com/sulu/sulu-minimal
- [x] https://github.com/sulu/sulu-docs
- [x] https://github.com/sulu/SuluArticleBundle
- [x] https://github.com/sulu/SuluFormBundle
- [x] https://github.com/sulu/SuluRedirectBundle
- [x] https://github.com/sulu/SuluAutomationBundle
- [x] https://github.com/sulu/SuluThemeBundle
- [x] https://github.com/sulu/SuluCommunityBundle
- [x] https://github.com/sulu/SuluCommentBundle
- [x] https://github.com/sulu/SuluSyliusProducerPlugin

# HandcraftedInTheAlps

- [x] https://github.com/handcraftedinthealps/RestRoutingBundle
- [x] https://github.com/handcraftedinthealps/ElasticsearchDSL
- [x] https://github.com/handcraftedinthealps/ElasticsearchBundle
- [x] https://github.com/handcraftedinthealps/ZendSearch

# MASSIVE ART

- [x] https://github.com/massiveart/MassiveBuildBundle
- [x] https://github.com/massiveart/MassiveSearchBundle
- [x] https://github.com/massiveart/husky

# Jackalope (PR created)

- [x] https://github.com/jackalope/jackalope
- [x] https://github.com/jackalope/jackalope-doctrine-dbal
- [x] https://github.com/jackalope/jackalope-jackrabbit
- [x] https://github.com/jackalope/jackalope-fs

# PHPCR

- [ ] https://github.com/phpcr/phpcr
- [ ] https://github.com/phpcr/phpcr-migrations
- [x] https://github.com/phpcr/phpcr-shell
- [ ] https://github.com/phpcr/phpcr-utils

/cc @sulu/core-team

**Comment by alexander-schranz** [comment]
Did find out that over [https://github.com/search](https://github.com/search) you can search for [`user:sulu filename:.travis.yml`](https://github.com/search?q=user%3Asulu+filename%3A.travis.yml&type=code). 

We should not forget that we have also other organizations repository which we maybe need to migrate:

 - [handcraftedinthealps](https://github.com/search?q=user%handcraftedinthealps+filename%3A.travis.yml&type=Code)
 - [massiveart](https://github.com/search?q=user%3Amassiveart+filename%3A.travis.yml&type=code) (searchbundle, buildbundle, husky (sulu 1.6 ui))

and maybe we also need to migrate the `jackalope` and `phpcr` packages because I think nobody else will do that:

 - [jackalope](https://github.com/search?q=user%3Ajackalope+filename%3A.travis.yml&type=code)
 - [phpcr](https://github.com/search?q=user%3Aphpcr+filename%3A.travis.yml&type=code)

**Comment by luca-rath** [comment]
Updated the issue description

**Comment by niklasnatter** [comment]
As far as I see, we managed to move all `Sulu`, `HandcraftedInTheAlps` and `MASSIVE ART` repositories 🎉 
Thanks everybody for working on this!

As we are not official maintainers of the `Jackalope` and `PHPCR` repos, I would propose to close this issue here.
