### ISSUE TITLE
Selection field type should use order of given ids for displaying items

### ISSUE THREAD

**Issue by timkoopmans50** [sulu/sulu#5728]
# Problem description
If you make an entity selection (https://docs.sulu.io/en/2.2/book/extend-admin.html) you can select multiple entities. In your controller you would handle saving it in this specific order to an intermediary entity (the component allows for re-ordering using drag and drop), and in the getter of your entity you would then simply retrieve and sort the entities before returning the array of id's. This array of id's is used to pre-fill the component when you load the "edit" form, but it is completely ignoring the order of the given array.

# Proposed solution
By default, order the list of the selection based on the keys of the array of id's that is provided by the getter of the entity, giving a programmer direct control over the order.

**Comment by alexander-schranz** [comment]
@timkoopmans50 can it be that your API does not keep in mind the order of the given `ids`. See as example: https://github.com/sulu/sulu/blob/40f01fe03dc4e4839745b1f25c68d9b476cbd16c/src/Sulu/Bundle/MediaBundle/Controller/MediaController.php#L301-L306

Or does your api return it in the correct order you send the `ids` request?

**Comment by niklasnatter** [comment]
Thanks for reporting this!

The `Selection` field type will load the selected entities by requesting the list API with an `ids` parameter. This `ids` parameter will contain the selected ids in the correct order. At the moment, the field type expects that the list API of the entity respects the order of the ids in the `ids` parameter. For example, the sulu-demo implements this sorting in the `DoctrineListRepresentationFactory`:
https://github.com/sulu/sulu-demo/blob/233bef35fb132bbb578434ccb58128caf3d36ee0/src/Common/DoctrineListRepresentationFactory.php#L66-L74

That said, I think it should be possible to adjust the `Selection` field type to sort the items by itself instead of relying on the API. That way there would be one thing less to think about when implementing the API for an entity. This is the code that loads the items for the given ids:
https://github.com/sulu/sulu/blob/2f268cf110816ff44270fc724fdd3cb8424fd0d2/src/Sulu/Bundle/AdminBundle/Resources/js/stores/MultiSelectionStore/MultiSelectionStore.js#L68-L77

In this method, I think we could just sort the content of `data._embedded[this.resourceKey]` to match the order of the `itemIds` before calling `this.set` to solve this 🙂

**Comment by niklasnatter** [comment]
Thanks for reporting! Fixed by #5784
