### ISSUE TITLE
Save and publish option is shown when creating a page without live permission

### ISSUE THREAD

**Issue by paul-staedtler** [sulu/sulu#5876]
| Q | A
| --- | ---
| Sulu Version | 2.2.3
| PHP Version | 7.4.15
| DB Version | 
| Browser Version | 

# Actual Behavior

When creating a new page in a web space the save and publish option is shown without the live permission and throws following exception when trying to do so:
`Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException:
Permission "live" in localization "de" for object with id "" and of type "Sulu\Component\Content\Document\Behavior\SecurityBehavior" not granted`
which makes sense because my test user doesn't have this permission.

# Expected Behavior

The save and publish option shouldn't be visible to users without the live permission.
Just like when editing an already existing page the option isn't shown which is the desired behavior.

# Steps to Reproduce

Give a user the permission to add new pages to a certain web space without live permission.
Then create and try to save and publish the new page.

**Comment by niklasnatter** [comment]
Thanks for reporting. I want to note that this **only happens when creating a page, not when editing one**. The reason is that the visibility of the toolbar actions is determined based on the object specific permissions. For a new page, no object specific permissions are available:
https://github.com/sulu/sulu/blob/aa692e8255750d21f5a287a420304c544c2a8619/src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php#L117-L118

Unfortunately, I am not sure if there is an easy way to fix this. We cannot conditionally add the toolbar actions to the view like we do in other places, because permissions for this view are dependent on the selected webspace in the frontend. This means that the frontend would need to evaluate if the respective permission is granted for the current webspace. 
As far as I know, we have not implemented anything in the direction of dynamic conditions like this at the moment.

**Comment by niklasnatter** [comment]
This should be fixed by #6221. Thanks for reporting it!
