### ISSUE TITLE
[REST] Get part of template properties

### ISSUE THREAD

**Issue by RSalo** [sulu/sulu#5880]
# Problem description

There is no solution out of the box to load part of template properties. For example, I have a bunch of custom properties in the template that sufficient decreasing page speed. It will be better if I would load one asynchronously with frontend requests.

# Proposed solution

Add default helper services for this purpose or documentation on how to do that thing correctly.

P.S. Close this issue if a similar exists.

**Comment by niklasnatter** [comment]
Hey,
I think we already talked about this in our Slack channel, but I will add my thoughts here again for completion.

I do not think such a feature fits into the `sulu/sulu` package. One of the basic ideas of Sulu is to pass the data that is used for rendering a page directly to the Twig template of the page. Additionally, Sulu provides twig extensions that allow for loading data like the navigation structure (`sulu_navigation_tree`) or data of another page (`sulu_content_load`). 
Both these mechanism run synchronously and operate inside of PHP. This allows content types such as the `media_selection` to pass a PHP object with methods like `isTypeOf()`. 

An API like described in this issue cannot return PHP object and needs to serialize the data in some way. This means that the data returned by the API is **inconsistent to the date that would be passed to the Twig template**. Furthermore, the data that is returned by such an API **must be rendered via Javascript instead of Twig**. This does not integrate well into the existing ideas and therefore should not be part of the `sulu/sulu` package in my opinion. 

That said, we are aware that there are a lot of usecases for loading the data managed in Sulu via an API. We decided to implement these APIs in a separate bundle. Have a look at the [`SuluHeadlessBundle`](https://github.com/sulu/SuluHeadlessBundle), if you are interested in this 🙂

**Comment by niklasnatter** [comment]
For completion, I want to add my thoughts on the following statements:

> There is no solution out of the box to load part of template properties

The `sulu_content_load` function allows to pass an array of properties which should be included in the result of the function. I dont think such a feature exists for the `SuluHeadlessBundle` yet. Feel free to create an issue if that would be important for you.

> I have a bunch of custom properties in the template that sufficient decreasing page speed

Sulu should be quite performant by default. I would recommend to investigate why these properties are slow in your case and if there are things that can be improved. Furthermore, Sulu will cache the rendered page in the `prod` environment, so these properties do not affect the page speed after the first request in the `prod` environment.

> It will be better if I would load one asynchronously with frontend requests.

As stated above, when using Sulu in the `prod` environment, only the first request will be slow. Also, loading data asynchronously will only affect the initial rendering. The user will still need to wait for the data that is loaded asynchronously if he is interested in that data. Furthermore, the asynchronous request will add an additional delay because it will be started only after the Javascript of the page was interpreted.

**Comment by alexander-schranz** [comment]
I could think about that example a selection could have an option like `resolve: false`:

```xml
<property name="page" type="single_page_selection">
       <param name="resolve" value="false" />
</property>
```

So in this case only the raw page id is returned e.g.:

```js
{
    "content": {
        "page": "fb3c4ecc-9d19-4fd1-9e4a-5e0ce7db20d4",
     }
}
```

This page id could be used to load all children, or uses a twig extension to load children, or when a category selection all pages with a specific category id could be loaded. I think there are usecases where you don't also in the content management part that maybe just an id is returned.

From performance of the first request I think this is not the right choice as you should there more spend time to improve that your `HttpCache` and that all your user get a cached page fast responded. So content pages are returned without accessing any database. There are good caching mechanism when using varnish the grace mode which will always return your user a cached page and will refresh pages in the background.

**Comment by RSalo** [comment]
Oh, exactly! I should try Headless bundle yet. I will close this ticket if it fits for me😁

**Comment by niklasnatter** [comment]
Closing this because of the reasons explained above 🙂
