### ISSUE TITLE
User Roles field is marked as mandatory but is not

### ISSUE THREAD

**Issue by johann-mok** [sulu/sulu#5886]
| Q | A
| --- | ---
| Sulu Version | 2.2.4
| PHP Version | 7.4.15

# Actual Behavior

Its possible to save users permissions without selecting any user roles.

# Expected Behavior

There should be an error message.

# Steps to Reproduce

Edit an user inside of the permissions tab and remove all user roles.

**Comment by alexander-schranz** [comment]
@johann-mok the role is not required. You can create users and then later define which role you want to add to them. The user is not a required field. It could also be just a user of the website which don't use the sulu roles and security system. So this is correct behaviour that you can create a user without role.

I will keep this open as the form currently seems to tell that there need to be a user role but this is incorrect, there could be users without a role also when its not recommended to be used this way its possible when using on your website a normal [doctrine user provider](https://symfony.com/doc/current/security/user_provider.html#entity-user-provider). Beside the [`role_assignement`](https://github.com/sulu/sulu/blob/aa692e8255750d21f5a287a420304c544c2a8619/src/Sulu/Bundle/SecurityBundle/Resources/config/forms/user_details.xml#L60) field type seems currently not support the mandatory flag.

**Comment by niklasnatter** [comment]
As @alexander-schranz already explained, there are valid usecases creating a user without a roles. To reflect this, the misleading `mandatory` flag was removed in https://github.com/sulu/sulu/pull/5887.

The mandatory flag does not work for the `role_assignments` field-type because of the reason described in https://github.com/sulu/sulu/issues/5426 and https://github.com/sulu/sulu/issues/2938. This could be fixed in the `2.3` release by implementing a `PropertyMetadataMapper` like in https://github.com/sulu/sulu/pull/5666. 

I think the `role_assignments` field-type is not something that should be reused in another form and therefore I dont think we should invest a lot of effort into this. But we will happily review a pull request if somebody is interested in contributing this! 🙂

**Comment by johann-mok** [comment]
@alexander-schranz @nnatter it makes absolutely sence. The mandatory true flag was the confusing point. :)
