### ISSUE TITLE
Sulu does not always redirect to login while navigating in case of an expired session

### ISSUE THREAD

**Issue by alexandersch** [sulu/sulu#5916]
| Q | A
| --- | ---
| Sulu Version | 2.2.7
| PHP Version | 7.4
| DB Version | MySQL 5.7
| Browser Version | Chrome 89.0.4389.90

# Actual Behavior

If your sulu admin session has expired, because of inactivity, and you navigate to any page in the CMS, it doesn't always log you out. Despite of the 401 responses on the requests. It only logs you out when a request is handled by the Requester service.

# Expected Behavior

I expect to be logged out on any request when your session has expired.

# Steps to Reproduce

1. Login to CMS
2. Remove the `SULUSESSID` cookie
3. Navigate to media for example, or contacts, webspaces overview. This won't log you out.
4. It does log you out when navigating to snippets or search for example.

# Possible Solutions
@nnatter pointed out that it might be because the requests are not all handled by the requester service.
"It looks like the metadataStore that is used by the form uses fetch directly instead of using the requester service that implements the logout handling:
[https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/AdminBundle/Resources/js/stores/metadataStore/metadataStore.js#L30](https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/AdminBundle/Resources/js/stores/metadataStore/metadataStore.js#L30)"

**Comment by niklasnatter** [comment]
Thanks for creating the issue! The automatic logout is added as hook of the `requester` service here:
https://github.com/sulu/sulu/blob/f8b1be3c0756325f4a986a65dbf0b0474e0eddbb/src/Sulu/Bundle/AdminBundle/Resources/js/index.js#L125

It looks like the `metadataStore` service does use `fetch` instead of the `requester` service. Therefore the automatic logout will not happen if such a request fails:
https://github.com/sulu/sulu/blob/f8b1be3c0756325f4a986a65dbf0b0474e0eddbb/src/Sulu/Bundle/AdminBundle/Resources/js/stores/metadataStore/metadataStore.js#L30-L42

 I have not investigated this in depth and therefore I am not sure if there is a reason for using `fetch` instead of the `requester` service. If there is a reason, we could solve this by calling the registered hooks (`Requester.handleResponseHooks`) in the `metadataStore` service too.

**Comment by alexander-schranz** [comment]
The metadatastore.js was implemented in https://github.com/sulu/sulu/pull/4671 I see there no comment why the requester was not used and I see currently not why the requester should not work. So I would say that we should change it to the requester service at for the `metadataStore.js`. 

@alexandersch do you want to create a PR for it?

**Comment by niklasnatter** [comment]
I could imagine that there is no way to access the `cache-control` information that is used here when using the `requester` service:
https://github.com/sulu/sulu/blob/f8b1be3c0756325f4a986a65dbf0b0474e0eddbb/src/Sulu/Bundle/AdminBundle/Resources/js/stores/metadataStore/metadataStore.js#L36-L39

**Comment by alexandersch** [comment]
So what do you guys suggest now, call the `Requester.handleResponseHooks` or replace fetch completely with requester service?

**Comment by niklasnatter** [comment]
I think I would favor to add a `Requester.fetch()` method that provides the same interface as the default `fetch` method but  calls the registered `Requester.handleResponseHooks` when the promise resolves. This would allow us to use the `Requester.fetch()` method as a direct replacement in all the places that use `fetch` directly at the moment 🙂

**Comment by alexandersch** [comment]
Sounds good, I could give that a try and see what I can do.

**Comment by niklasnatter** [comment]
Fixed in https://github.com/sulu/sulu/pull/6172 - thanks for reporting! 🙂
