### ISSUE TITLE
Save button is not enabled after changing the template of a page

### ISSUE THREAD

**Issue by michaelzangerle** [sulu/sulu#5927]
| Q | A
| --- | ---
| Sulu Version | 2.2.6
| PHP Version | 7.4.16
| DB Version | mySQL 5.7
| Browser Version | Version 89.0.4389.114 (Official Build) (64-bit)

# Actual Behavior

The safe button for a page is not clickable.

# Expected Behavior

The safe button for a page should be clickable if all required fields are present and have a proper value.

# Steps to Reproduce

I was able to reproduce it also on sulu.rocks

- Go to webspaces in https://sulu.rocks/admin/
- Create a new page
- Add a title
- Change the template to e.g. `Homepage`
- Try to click the safe button (it's deactivated)
- As a workaround you can make a change to some field or just click inside the resource locator field and the save button will be enabled

# Possible Solutions

**Comment by niklasnatter** [comment]
Thanks for reporting! 

It looks like the reason for this is a bit complicated 🙈  
The button is disabled because the form is marked as not dirty in this callback:
https://github.com/sulu/sulu/blob/5c7a15c250c01ee4337f1fd1c44a34b2e9035147/src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js#L58-L63

The callback is executed because the `Form` container is rerendered because the value of `store.loading` changes:
https://github.com/sulu/sulu/blob/5c7a15c250c01ee4337f1fd1c44a34b2e9035147/src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js#L163-L165

The value of `store.loading` changes because these lines are executed when the type of the form is changed:
https://github.com/sulu/sulu/blob/5c7a15c250c01ee4337f1fd1c44a34b2e9035147/src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js#L82-L86

**Comment by alexander-schranz** [comment]
This is fixed by #6115
