### ISSUE TITLE
Prefix or "format" for route field type

### ISSUE THREAD

**Issue by WouterCypers** [sulu/sulu#5932]
# Problem description

This is related to [this discussion on Slack](https://sulu-io.slack.com/archives/C0430GGCV/p1617980544464500).

For custom entities, routes can be edited via the `route` field type. This means the user can edit the entire route. In some situations, this might not be desirable. It would be helpful to be able to define a prefix. My goal here is that the user should be able to edit the “slug”, which is autogenerated, but cannot change the “prefix”.

**For example:**
For entity `Artist` with title “Claude Monet”, the route should be `artists/claude-monet`. The user should be able to change slug `claude-monet`, but not the `artists` part of the route.

![Screenshot 2021-04-09 at 17 01 24](https://user-images.githubusercontent.com/22339968/114209248-b3f3b180-995e-11eb-99ce-513e4423ecb6.png)

# Proposed solution
Here are some possible solutions:

## 1. `prefix` parameter 

A parameter `prefix` could provide a way to configure a route prefix.
`<param name="prefix" value="artists/" />`

## 2. `format` parameter
A parameter `format` might be even more flexible, as the slug can be seen as a wildcard. This would allow prefixes and suffixes.
`<param name="prefix" value="artists/*" />`

Now, there is a more complex situation I do not really have an answer for. Following on the example with `Artist`, consider an `Artwork` entity. Each `Artitst` relates to multiple `Artwork` entities. Now if we want to create routes for `Artwork` entities, we might need the name of the `Artist` entity. For example, for `Artwork` with title "Water Lilies" by Monet, we have route `artists/claude-monet/water-lilies`. Maybe this can be achieved by configuring the `schema` option?

Note that the entire route should be unique, not the slug. If two different artists relate to an `Artwork` with the same `title`, then routes like `artists/claude-monet/painting` and `artists/picasso/a-painting` should be able to coexist.

**Comment by manuxi** [comment]
Would be a nice feature. Keep the translation in mind.

**Comment by niklasnatter** [comment]
In the case of pages, the behaviour of the input field depends on the configured resource locator strategy of the webspace. The `tree_leaf_edit` strategy will render everything until the last slash as read-only and will allow to only edit the part after the last slash:
https://docs.sulu.io/en/latest/book/webspaces.html#resource-locator-optional

I created a PR (#5933) to make this behaviour configurable for the `route` content type in the XML template. This might be a bit less flexible than a new `format` param, but I would prefer this solution because the functionality is already here and it is consistent with the behaviour for pages 🙂

**Comment by niklasnatter** [comment]
> Now, there is a more complex situation I do not really have an answer for. Following on the example with `Artist`, consider an `Artwork` entity. Each `Artitst` relates to multiple `Artwork` entities. Now if we want to create routes for `Artwork` entities, we might need the name of the `Artist` entity. For example, for `Artwork` with title "Water Lilies" by Monet, we have route `artists/claude-monet/water-lilies`. Maybe this can be achieved by configuring the `schema` option?

This is not possible at the moment when using live generation because the title of the assigned artist is not available when evaluating the configured route schema (only the value of the fields with a `sulu.rlp.part` tag will be available). I think it should be possible when not using live generation but generating the route only on the first save of the entity (like in the `SuluArticleBundle`: https://github.com/sulu/SuluArticleBundle/issues/514).

So I think this is more related to what is usable inside of a route schema when using live generation than to a prefix feature. Therefore I would prefer to handle this in a separate issue if it is important for you 🙂

**Comment by WouterCypers** [comment]
I understand that it is a separate and more difficult issue to do live generation depending on values set in other entities. Indeed, it would probably be better to generate the route on the first save.

I think PR #5933 already adds some great functionality. Thank you!

**Comment by niklasnatter** [comment]
I am closing this as #5933 was merged. Feel free to create a new issue and reference this one if #5933 does not solve one of your usecases! 🙂
