### ISSUE TITLE
Searching in admin does not work on Sulu 2.3-RC

### ISSUE THREAD

**Issue by alexandersch** [sulu/sulu#6057]
| Q | A
| --- | ---
| Sulu Version | 2.3-RC
| PHP Version | 7.4.x
| DB Version | MySQL 5.7.x
| Browser Version | Chrome, latest version

# Actual Behavior
When searching on the search page in the admin it responds with an error:
```Argument 5 passed to Sulu\\Component\\Rest\\ListBuilder\\PaginatedRepresentation::__construct() must be of the type int, array given, called in /home/cms/www/vendor/sulu/sulu/src/Sulu/Bundle/SearchBundle/Controller/SearchController.php on line 124```

# Expected Behavior
I expect it to find 0 or more results. No errors.

**Comment by alexander-schranz** [comment]
Seems like this is an issue on the MassiveSearch side. Since Elasticsearch 7 `total` will be return under `['total']['value]`.

I would adjust the code maybe to something like:

```php
// backward compatibility between elasticsearch 7 to elasticsearch 6 and lower
$total = isset($res['hits']['total']['value']) ? $res['hits']['total']['value'] : $res['hits']['total'];

return new SearchResult($hits, (int) $total);
```

https://github.com/massiveart/MassiveSearchBundle/blob/9682a640937bd5006025f5e776bad7b90c7cf25c/Search/Adapter/ElasticSearchAdapter.php#L235

We did something similar here in our ongr elasticsearchbundle fork to support multiple elasticsearch versions: https://github.com/handcraftedinthealps/ElasticsearchBundle/blob/58aa902eccaa493862796963bb22d56646619bee/Result/AbstractResultsIterator.php#L104-L110

Reference to Elasticsearch changes: https://www.elastic.co/guide/en/elasticsearch/reference/7.12/breaking-changes-7.0.html#hits-total-now-object-search-response

**Comment by alexander-schranz** [comment]
This is fixed in the latest `massive/search-bundle` release. Run the following command to update it:

```bash
composer update massive/search-bundle
```
