### ISSUE TITLE
Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by wardaari** [sulu/sulu#6094]
| Q | A
| --- | ---
| Sulu Version | 2.3.0
| PHP Version | 7.4.3
| DB Version | mysql  Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64
| Browser Version | Chrome 90.0.4430.212 

# Actual Behavior

Cannot read property 'code' of undefined

# Expected Behavior

Should build the admin JS with no errors

# Steps to Reproduce

```
cd assets/admin
delete node_modules
delete package-lock.json
npm install
npm run build
```

**Comment by alexander-schranz** [comment]
Hello,

Please make sure the delete all `node_modules` and `package-lock.json` directories. Because there could also be cached directories inside the `vendor` directory. Also if you have a `node_modules` directory in your project root. This need also be removed.

See also the following documentation and maybe you can try to use docker to generate your custom admin build:
https://docs.sulu.io/en/2.2/cookbook/build-admin-frontend.html#solution-2-build-manually-with-docker

Also could would to be know what you did change in your `index.js` which does trigger this error?

**Comment by wardaari** [comment]
Hello,
I noticed the bug when I was trying to add fonts to the CKEditor following the docs [here](https://github.com/sulu/sulu-demo/pull/77). Is that doc still valid or is there another way to do this? I am new to Sulu and Symfony in general (coming from Laravel stack)

**Comment by alexander-schranz** [comment]
@wardaari Extending the CKeditor is normally something we not recommend as in our view the content should be not connected to the presentation and so fonts should be controlled by your css and not by the content manager, but we know that still some devs want to give there control to the content manager that's why there is an example. 

For your problem I think the easiest way for us the reproduce it if you create a sample repository based on [`sulu/skeleton`](https://github.com/sulu/skeleton) so we can see what you did change.

Also I did see you use `2.2.3` there are known issues with old versions you should update atleast to latest patch release which is `2.2.10`: https://docs.sulu.io/en/latest/upgrades/upgrade-2.x.html and try it then again.

**Comment by wardaari** [comment]
@alexander-schranz deleting all the node_modules and the package-lock.json files everywhere and then running `php bin/adminconsole sulu:admin:update-build` seems to have done the trick. Thanks for your help
