### ISSUE TITLE
Error when clearing cache — Directory not empty

### ISSUE THREAD

**Issue by rantnik** [sulu/sulu#6289]
| Q | A
| --- | ---
| Sulu Version | 2.2.4
| Browser Version | Chrome/93.0.4577.82 YaBrowser/21.9.0.1044 Yowser/2.5 Safari/537.36

# Actual Behavior

Hi! I’m facing the problem of deleting the cache. The cache is not deleted in the admin panel and through the command `rm -rf var/cache`.
It shows a strange error that there are files in the folder, so it is not deleted.
The permissions are exactly set up correctly. The number of cache files is ~6000-8000.

![image (9)](https://user-images.githubusercontent.com/75247694/136439163-9d96ecb9-0bef-4785-968c-8cb5eb345506.png)

Apparently it was the `rm -rf var/cache` command. While the command is running in the cache folder new files have time to be created. When I delete with the command `php bin/adminconsole fos:httpcache:clear` the process takes a long time, but it still works.
In the admin panel, the cache is removed, but it takes a long time. Sometimes I have to log in again and press the reset cache button a second time and wait a few minutes.

# Steps to Reproduce

When I'm using `rm -rf var/cache/*`
I see an error:
rm: cannot remove 'var/cache/common/prod/http_cache/@/tags/B/C/PU-vXSopn2SJPbqHLhxQ': Directory not empty

# Possible Solutions

A possible solve the problem is to rename the folder. By renaming the cache directory before removing it here:
https://github.com/sulu/sulu/blob/2.3/src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php#L105-L113
renaming should be faster than deleting and will prevent new request from write into the directory while deleting.

**Comment by alexander-schranz** [comment]
@rantnik Rename before remove I think is fine. Do you want to create a Pull Request for it?

Still I must recommend you that `rm -rf var/cache` is nothing which should be run on a production server. When you deploy you should go with a blue green deployment, which can example achieved over  [php deployer](https://sulu.io/blog/deploy-sulu-with-deployer), which can deploy an already build up cache directory and race conditions like "cannot remove 'var/cache/common/prod/http_cache/@/tags/B/C/PU-vXSopn2SJPbqHLhxQ': Directory not empty" does not appear then.

The default http cache is based on PSR 6 cache storage of the http cache bundle: https://github.com/Toflar/psr6-symfony-http-cache-store. As the default cache is filebased it has some limitations. I could think that the cache clear can be optimized when there is only 1 webspace so instead of tag based invalidation there just all things are invalidated. Which I think should be faster. Not sure how things can be optimized for multi webspace setup here. Here I think the PSR6 storage will get in some point in its limitaton. I think if you have a big http cache and a high traffic side an alternative http cache like [Varnish](https://docs.sulu.io/en/2.3/cookbook/caching-with-varnish.html) which is supported by sulu is better suited.

@rantnik Would be interesting how big your site is, how many cacheable pages there are and if there is some kind of user context based caching used? To know when this kind of big response times in cache clear is happening.

**Comment by alexander-schranz** [comment]
@rantnik Thx for the proposal. The renaming was done in #6290 and will be part of the next release.

**Comment by rantnik** [comment]
@alexander-schranz thanks a lot!
The website is not very big - about 200 pages. The users are about 700 people a day.
The menu and footer are large. For example in the footer about 50 links (almost a site map). But I do not think it can have any effect.

cache statistics (a lot of cache files were, Jule 21)
.: 53108
./preview: 1111
./website: 1117
./common: 47661
./admin: 3219

After clearing the cache a few days have passed:
.: 8049
./website: 779
./preview: 715
./admin: 2922
./common: 3633

**Comment by alexander-schranz** [comment]
Thx for the response. You are using the 2.2.4 version of sulu? And which symfony/cache package version is used in your case?

**Comment by rantnik** [comment]
@alexander-schranz 
We have the following lines about the cache in the `composer.json` file:
```
"require": {
  "friendsofsymfony/http-cache-bundle": "^2.8",
  "twig/cache-extra": "^3.3"
}
```

Sulu 2.2.4.

**Comment by alexander-schranz** [comment]
Can you share result of `composer info` to get your locked versions.

**Comment by rantnik** [comment]
```
symfony/cache    v5.2.3   
Provides an extended PSR-6, PSR-16 (and tags) implementation
```
[composer-info.pdf](https://github.com/sulu/sulu/files/7312319/composer-info.pdf)

**Comment by alexander-schranz** [comment]
Maybe improvements can be make to upgrade the `symfony/cache` and `toflar/psr6-symfony-http-cache-store` storage package to a newer version. I created a seperate issue to maybe optmize cache invaldiation by avoiding tag invalidation when only one webpspace exist here: #6291. But if you really are on 2.2.4 there is no tag invalidation on webspace level done so you should not be effected by that.
