### ISSUE TITLE
If no Cache Proxy Client is enabled, caching in the browser is disabled

### ISSUE THREAD

**Issue by ampaze** [sulu/sulu#6303]
| Q | A
| --- | ---
| Sulu Version | 2.2.16
| PHP Version | 8.0.8

# Actual Behavior

If in `sulu_http_cache.yaml` no Cache Proxy Client is enabled, the resulting header is

`Cache-Control: no-cache, private`

This is probably related to #6301.

# Expected Behavior

The configured max-age in template.xml (\<cacheLifetime\>) should be used, and a cache-control header should be send, like

`Cache-Control: max-age=10, public, s-maxage=10`

# Steps to Reproduce

See above

**Comment by alexander-schranz** [comment]
@ampaze We have no such issues with this on our installation, so I think this is something in your project. Keep in mind caching is only active on stage/prod environment. Have as example look at https://sulu.rocks/en which correctly set the `Cache-Control` headers are here correctly set.

Also keep in mind you are not allowed to access any `Session` or service which start a `Session`. This will automatically make the request private as it is user specific by Symfony. Because of security reasons sulu and symfony does then not cache the response.

If you want to have user context base caching (role based)  you would need have a look at the following documentation: https://docs.sulu.io/en/2.3/cookbook/user-context-caching.html.

https://github.com/symfony/symfony/blob/8523047927fc91ece4c474347a17bbadacf5ea38/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L190-L196

**Comment by ampaze** [comment]
> We have no such issues with this on our installation,

According to https://github.com/sulu/sulu-demo/blob/master/config/packages/prod/sulu_http_cache.yaml there is a proxy client enabled (varnish) in the demo.

This is not a session problem, as it will work as soon as I enable varnish without actually having varnish running.

**Comment by alexander-schranz** [comment]
You need atleast a proxy client else caching is not active, by default its symfony cache. On the demo we use varnish. When one is enabled the cache headers should be correcty set. 

This is done by: https://github.com/sulu/sulu/blob/2.x/src/Sulu/Bundle/HttpCacheBundle/CacheLifetime/CacheLifetimeEnhancer.php

So I think your issue is that you try to use `nginx` or try to disable symfony or varnish which is currently official not supported by sulu. I think to add support for nginx or other caches you would need to add them also to the sulu http cache configuration.

So think this is related to https://github.com/sulu/sulu/issues/6302

**Comment by ampaze** [comment]
Thanks, I get that now. 

As I wrote here https://github.com/sulu/sulu/issues/6301#issuecomment-944281144 
for me the max-age header is not primarily a server side caching thing. 

It makes no sense to me to not have the possibility to tell the browser to cache a page without also having to use a certain supported server side cache.
