### ISSUE TITLE
[Caching] Use maxage (and/or s-maxage) instead of X-Reverse-Proxy-TTL by default

### ISSUE THREAD

**Issue by ampaze** [sulu/sulu#6307]
# Problem description

Currently Caching in Sulu is opinionated, as it uses **X-Reverse-Proxy-TTL** by default which works fine with the currently supported cache backends (e.g. Symfony and Varnish) but can be confusing, limits the cache backends that could be used and makes caching more complex overall.

# Proposed solution

Make the use of X-Reverse-Proxy-TTL optional, as it is only needed if you really need / want to control three separate TTLs.
In a normal setup max-age is more than enough and if you want to have separate caching times for the browser and your own cache backend then max-age and s-max-age are sufficient.

This also means that max-age and s-maxage would become enabled and useable even without a caching backend and on a per template basis.

## Additional context:

X-Reverse-Proxy-TTL is not a default or industry standard by any means:

https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/headers.html#reverse-proxy-ttl

> This keeps your s-maxage free for use with reverse proxies not under your control.

And this is really a very specific use case not worth thinking about for most users.

**Comment by alexander-schranz** [comment]
@ampaze The `X-Reverse-Proxy-TTL` is a widely spread technic to differ cache lifetimes between the own cache server and third proxy cache lifetimes.
We will not make the usage of `s-maxage` default because we would lose then the advantage to define cache lifetimes for third party proxies, and you don't want that a third party proxy caches your page more then some minutes.
So the `X-Reverse-Proxy-TTL` will stay as default behaviour for specially symfony and the varnish cache, which are the widely used caches used by Sulu.
Still if we will target to add support for `nginx` (#6302) we will make it easier to set the cachelifetime over `s-maxage` or make it depending on the used adapter if `x-reverse-poxy-ttl` or `s-maxage` is used, but from our point of view it does not make sense as to make `s-maxage` when using the symfony or varnish adapter.
Keep in mind that nginx is a very basic http cache, it does not support tag based invalidation. Also Sulu Features like Segments, Audience Targeting or when using User Context Based caching are in caches like nginx or other third party caches not supported. So only for some basic sites the nginx cache make sense. Most stays there just with symfony cache for this sites.
I hope I could give you an overview why it is this way, as said the s-maxage issue is something which need to be target when tackling the nginx support (#6302). Still thank you for giving your view on this topic.

**Comment by ampaze** [comment]
> The `X-Reverse-Proxy-TTL` is a widely spread technic to differ cache lifetimes between the own cache server and third proxy cache lifetimes.

I disagree about the widely spread part 😉  , Google has 4 pages for "X-Reverse-Proxy-TTL" and not even the [varnish documentation](https://varnish-cache.org/docs/7.0/search.html?q=X-Reverse-Proxy-TTL) contains anything about it. 
This seems more a case of everyone copying the same suggestions without asking why. Symfony support might also have something to do with it.

> We will not make the usage of s-maxage default because we would lose then the advantage to define cache lifetimes for third party proxies, and you don't want that a third party proxy caches your page more then some minutes.

Changing the default does not lose you any advantage. If someone knows what he/she is doing they can just enabled it because they need it, not because it is the default.
At the moment you cannot define cache lifetimes for third party proxies or the browser at all, you can only set one single value for all pages. This is a direct result of using non standard headers in the first place.

If you are really concerned with those third party proxies, which I doubt are a real world issue, just set s-maxage to 0 or  cache-control: private in the cache backend. Problem solved.

----

Now for some speculation 😬 

>  Also Sulu Features like Segments, Audience Targeting or when using User Context Based caching

While I obviously don't have any real numbers, I would argue that these features are not something a typical webpage needs, that is maybe running on some webhoster. For those the key is performance from caches, using the http standard techniques.

**Comment by ampaze** [comment]
> If you are really concerned with those third party proxies, which I doubt are a real world issue, just set s-maxage to 0 or cache-control: private in the cache backend. Problem solved.

Just to add to this a bit, in our HTTPS everything world, there will never be a cache you don't control between you and the client browser. So s-maxage will almost never be used if your own cache ignores it.

**Comment by alexander-schranz** [comment]
The usage of a x-reverse-proxy-ttl was discussed by us internal when the HttpCache was implemented. The first version had s-maxage we then fast replace it with a custom header because of some problems and better controlling about the cache.

Sulu will always require a cache provider at current state there is only Symfony Cache and the Varnish with the sulu.vcl official supported. This official supported caches work out of the box and so if you using them as documented you don't care much about x-reverse-proxy-ttl.

I understand that it is frustrating in your case as you wanted to use nginx as a proxy, we currently does not have yet support for it. It was since longer in discussion but was never a priority and you seems the first one of the first one requesting it. So I can just say we will not change the default behaviour, but we are willing to add support for nginx, which we will provide a nginx docs how to configure it correctly using the x-reverse-proxy-ttl and we will provide a cache subscriber which will make usage of the s-maxage when the nginx proxy is used.

**Comment by chirimoya** [comment]
@ampaze first at all, thank you for your feedback. Adding my tow cents now. 

The default caching behaviour of Sulu relies on the Symfony/FOS HTTP cache. We also strongly recommend using an HTTP cache. Rendering complex webpages with all the unstructured data and references is a quite expensive task you definitely want to avoid doing for every request.

Why we use a custom TTL header is also quite good explained in the FOS HTTP Cache documentation: https://foshttpcache.readthedocs.io/en/stable/symfony-cache-configuration.html#custom-ttl

**Comment by ampaze** [comment]
@chirimoya & @alexander-schranz Thanks for taking the time to take a look at it again. I will use the custom `CacheLifetimeEnhancer` as suggested in #6301.

> Why we use a custom TTL header is also quite good explained in the FOS HTTP Cache documentation: https://foshttpcache.readthedocs.io/en/stable/symfony-cache-configuration.html#custom-ttl

Yes. This is was a valid reason before everyone started to use https and now we are kinda stuck with it.

>  So I can just say we will not change the default behaviour, but we are willing to add support for nginx, which we will provide a nginx docs how to configure it correctly using the x-reverse-proxy-ttl and we will provide a cache subscriber which will make usage of the s-maxage when the nginx proxy is used.

I have spend a lot of time with the nginx cache, which is very basic as you have noted. I don't think it supports something like `x-reverse-proxy-ttl`. Glad to help with supporting nginx cache better though. 

Btw: Just finished implementing Tagged Cache Invalidation with nginx, which requires write access to the cache directory. I will see what the FOSHttpCache team thinks about it.

**Comment by ampaze** [comment]
> I have spend a lot of time with the nginx cache, which is very basic as you have noted. I don't think it supports something like `x-reverse-proxy-ttl`. Glad to help with supporting nginx cache better though.

Just had a look, nginx supports the `X-Accel-Expires`-Header for the same purpose. So if the header name was configurable in Sulu, nginx would be covered.

**Comment by alexander-schranz** [comment]
@ampaze the new RFC9213 will maybe change this in the future. https://github.com/symfony/symfony/issues/47288

**Comment by ampaze** [comment]
Thanks for the heads up.
