### ISSUE TITLE
Admin Texteditor (CKEditor) has no way to switch to code/html view

### ISSUE THREAD

**Issue by ampaze** [sulu/sulu#6345]
| Q | A
| --- | ---
| Sulu Version | 2.2.16 (at least since 2.2.11)

# Actual Behavior

Clicking the `<>` Symbol inserts `<code></code>`

# Expected Behavior

In Sulu 1.6 clicking on <> switched to the html source code view and allowed to edit the HTML by hand.

----

We only noticed this after upgrading from 1.6 to 2.2.11, as the meaning of `<>` changed but not the icon, maybe this was missed.

**Comment by alexander-schranz** [comment]
Hello @ampaze,

It was not missed, the new CKEditor 5 did not support HTML Edit as it uses a internal format and so supports only some kind of minimal HTML output/input. This does also fit more how Sulu should be used as the Texteditor in sulu is like in other systems designed for Text and other things should be handled over content types or even block types specific for that use case. [Seperation content from presentation](https://sulu.io/guides/templating-and-structured-content-in-sulu#separating-content-from-presentation).

Nevertheless ckeditor 5 did in the last release add a new **experimental HTML Plugin** which would readd the old source code edit. So in future it should be able to readd source code mode. If sulu will ship the plugin need to be discussed. I personally more about being here more strict because the TextEditor in 1.6 was also a lot misused, instead of building good reusable block types.

**Comment by ampaze** [comment]
Hi @alexander-schranz 

Thanks for the info. While direct HTML access might be misused, WYSIWYG editors are quite often not really behaving in the correct way or get stuck on themselves. 

I am all for separation of content from presentation, but you have to balance it. The end result of full separation would be to have one block for the h2, one block for paragraph which inside has a block for text, then one block for bold text etc. and you would not need WYSIWYG at all.

For saving the content, HTML must still be coming out and going into the editor. So SULU could just have a function to toggle WYSIWYG mode. No need to wait for CKEditor.

**Comment by alexander-schranz** [comment]
@ampaze as said the Ckeditor 5 has a limited HTML support. It will strip all away which it does not know. So you can not just add a new class to a tag, the CKEditor 5 will strip this things just away as it does not know them. We will not build our own view source plugin or functionality as it will have no functionality which you can not do in the WYSIWYG. We will as said maybe ship the official full HTML support when it lands in the CKEditor version we are using. The current used CKEditor version does not support this kind of things. So if you need this you need to wait until CKEditor is upgraded to a newer Version which can the experimental HTML Support Plugin be added.

We are currently in the Phase of 2.4 and @nnatter is working currently on the js package upgrades, so maybe in 2.4 you will be able to add the experimantal HTML Plugin of CKEditor 5 to it.

PS: if you are creating block for h2, bold, ... you are doing the opposite of seperation of content from presentation as you directly create block types which represent a presentation. Do not see block types as a single property they should be more text block with (title, description), quote (text_area, contact, ..). But at the end you are totally free how to use them just see it from content manager perspective whats best for them.

I will close this issue as it say this issue is more part of ckeditor 5 and will depend on that be supported or not.

**Comment by ampaze** [comment]
> It will strip all away which it does not know. So you can not just add a new class to a tag, the CKEditor 5 will strip this things just away as it does not know them.

So this means someone upgrading Sulu from 1.6 to 2.x will potentially loose content just by saving a page?

Are valid html tags (like `<hr>`) always preserved?

**Comment by alexander-schranz** [comment]
Sorry for the circumstances I don't think `<hr>` is kept as ckeditor 5 will strip all things which the editor does not know or have plugin for it. For more you need to check ckeditor [docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migration/migration-from-ckeditor-4.html#existing-data). Sadly this change was missed to be missed in our UPGRADE.md and was not explicit added which effects the new editor has on the content.

If you need a `<hr>` you can add the hr plugin of ckeditor 5 and it will preserve that tag. See as example: https://github.com/sulu/sulu-demo/pull/77

**Comment by niklasnatter** [comment]
For completion, I would like to the lengthy issue about the missing `View Source` functionality in the ckeditor5 repository: https://github.com/ckeditor/ckeditor5/issues/592. The issue contains multiple readworthy comments about the limitations/tradeoffs of the feature and why it was not included in ckeditor5 initially.

Sulu 2.4 will update the integrated ckeditor package to version 31. With the new version, you will be able to add the [`@ckeditor/ckeditor5-html-support` package](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html) in your project like described in https://github.com/sulu/sulu-demo/pull/77 if you need this functionality.

**Comment by ampaze** [comment]
Thank you both :)

I realize that this is very difficult to keep track of, a warning in the upgrade docs seems to be very useful.

In my humble opinion CKEditor seems to be moving away from the use case that Sulu needs. They want to be a Rich Text Editor like Word with many many features that is way beyond basic text formatting and semantic structuring.

> If you need a `<hr>` you can add the hr plugin of ckeditor 5 and it will preserve that tag. See as example: sulu/sulu-demo#77

This is what I did.
