### ISSUE TITLE
Customizing ckeditor bar

### ISSUE THREAD

**Issue by romain35132** [sulu/sulu#6445]
Hi, 

I'am currently working on a Sulu 2.3 project and I want to add some features to my ckeditor toolbar. 
At first, I'd like to add some new styles in the dropdown bar, but I don't find how to do that. Where can I find some examples of adding new styles in this dropdown bar ? 

![image](https://user-images.githubusercontent.com/22448580/148371991-deb21b97-7808-4263-80bf-f78f3d06dc40.png)

Also, I did not find any way to add some images, but I red that Sulu does not work really good when we do that, and that's why this functionality has been abandonned.  Do you confirm that is not recommended to do that ?

Thank for the answers !

**Comment by CVogel** [comment]
Hi Romain,

I hope this helps you to get started on your first question:

```javascript
/* assets/admin/app.js */
// Add project specific javascript code and import of additional bundles here:
import {ckeditorConfigRegistry} from 'sulu-admin-bundle/containers';
ckeditorConfigRegistry.add((config) => ({
    heading : {
        options: [
            ...config.heading.options, //keep all other headlines
            {
                model: 'custom_div', //unique name in editor, the xml-element that is stored
                view: {
                    name: 'div', //html element on website
                    classes: 'text-blue-500' //css class on website
                },
                title: 'Custom DIV', //Title in ckeditor
                class: 'ck-heading_paragraph' //css class in editor, this class must be available in admin css code
            }
        ]
    }
}))
;
```

I've got the first pointers from demo project https://github.com/sulu/sulu-demo/pull/77

And you'll need to build the admin frontend application following the chapter in the cookbook: https://docs.sulu.io/en/2.4/cookbook/build-admin-frontend.html

Then I've read how to configure the heading feature in ckeditor5 here https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#configuring-custom-heading-elements

Unfortunately the editor will display those customs format only as block level elements.

As an addition how to remove items from the toolbar, because I've just found out:
```javascript
/* assets/admin/app.js */
// Add project specific javascript code and import of additional bundles here:
import {ckeditorPluginRegistry, ckeditorConfigRegistry} from 'sulu-admin-bundle/containers';
ckeditorConfigRegistry.add((config) => ({
    toolbar: {
        removeItems: [
            /** 
              I've uncommented the elements I want to keep, so you can see the names of all toolbar items.
              So this removes  'strikethrough', 'subscript', 'superscript' and 'code'
            */
            // 'heading', 'bold', 'italic', 'underline',
            'strikethrough', 'subscript', 'superscript', 
            // 'bulletedlist', 'numberedlist', 'alignment', 'externalLink', 'internalLink', 'insertTable',
            'code',
        ]
    }
}))
;
```

See also https://ckeditor.com/docs/ckeditor5/latest/features/toolbar/toolbar.html#basic-toolbar-configuration
and https://github.com/ckeditor/ckeditor5/issues/7945#issuecomment-743112238

I'm secretly planning to extend the sulu demo pull request https://github.com/sulu/sulu-demo/pull/77 and also add to the documentation https://github.com/sulu/sulu-docs/issues/320 once I've managed to create a copy of the ckeditor5 heading plugin for custom inline elements. But it will take a few more weeks.

Regards,
Christian
