### ISSUE TITLE
Different page templates based on different webspaces for the same page type

### ISSUE THREAD

**Issue by Mrkisha** [sulu/sulu#6864]
# Problem description
As A user, I should be able to set specific template for page type per webspace.

# Proposed solution
Lets say I have multi-website setup in sulu with webspaces **webspace1** and **webspace2**. They both use same page type **article**. However I want the page template structure (html) for webspace2 to be different than webspace1. Then I should be able to specify, possibly in webspace2 xml to use specific template for article page type.

I though `default-templates.default-template` or `templates.template` would do the trick. When I run `php bin/adminconsole sulu:content:validate:webspaces` to validate webspaces I get error `The template "<name of template>" is not valid for the webspace "<name of webspace>". Either it does not exist or was excluded from the webspace.`

**Comment by alexander-schranz** [comment]
This is already possible via `themes` and the SuluThemeBundle which is build on top of the SyliusThemeBundle.

You specify in `webspace1` the  `<theme>app/webspace1</theme>` and in `webspace2` the `<theme>app/webspace2</theme>` and so you can have different HTML structure. You even can themes build on top of the other themes. Have a look at the docs of the SyliusThemeBundle for more:

 - [https://github.com/sulu/SuluThemeBundle/](https://github.com/sulu/SuluThemeBundle/)
 - [https://github.com/Sylius/SyliusThemeBundle](https://github.com/Sylius/SyliusThemeBundle)

PS: the validate command does not work for themes because it is third party and can not validate if the template exists.

**Comment by Mrkisha** [comment]
Thank you. I though theme is more off to change the styles rather than templates as well.

**Comment by alexander-schranz** [comment]
@Mrkisha see it more the other way around you dont need themes to include different css based on a webspace key but you need theme when you want to overwrite templates.

**Comment by Mrkisha** [comment]
@alexander-schranz I got it.

I've made it work. 
However I think one thing is missing from documentation and that is that structure of template folder and files have to be exact as in <project>/template folder.
