### ISSUE TITLE
Error: HttpCache should not forward any response without any cache expiration time to the store

### ISSUE THREAD

**Issue by nurtext** [sulu/sulu#6995]
| Q | A
| --- | ---
| Sulu Version | 2.5.6
| PHP Version | 8.1.8
| DB Version | MariaDB 10.7.4
| Browser Version | Brave 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-Bit) 

# Actual Behavior

Fresh install on a prod environment, trying to download an uploaded media image using "Copy master file URL (Website)" and opened a new browser tab with that specific URL to the media image, resulting in the following error message.

![image](https://user-images.githubusercontent.com/148175/217548898-d35bf54a-fc44-4d06-803a-531c722e1329.png)

# Expected Behavior

Browser should download/display the desired media image.

**Comment by alexander-schranz** [comment]
Hello @nurtext,

This normally happens if you are using `APP_DEBUG=true` under `APP_ENV=prod` or `APP_ENV=stage` environment.

The current usage of the foshttpcache bundle can not be used in that combination under `APP_DEBUG=true` you need run under `dev` environment where the cache store is not enabled. And for `prod` and `stage` it is required to not run the it under the `APP_DEBUG` environment enabled. I also tested a current fresh `composer create-project sulu/skeleton` and so in my case all did work like expected. So I think your prod server has maybe somewhere `APP_DEBUG=true` defined this can be inside the `.env`/`.env.local` files or as real environment variable. So make sure to disable that on your prod env server.

**Comment by nurtext** [comment]
Thanks @alexander-schranz,

I was already checking my env vars as well as my .env file, but didn't noticed this yet. Will keep you posted regarding feedback on this topic.

Cheers,
Cedric

**Comment by nurtext** [comment]
Checked all values, it was indeed `APP_DEBUG=true` in combination with `APP_ENV=prod`! Thanks @alexander-schranz!
