### ISSUE TITLE
Allow datetime sorting in media data provider

### ISSUE THREAD

**Issue by Jupi007** [sulu/sulu#7011]
# Problem description

Currently, only title sorting is possible with the media data provider.
I would like to sort media by they creation datetime, and I'm surprised that it isn't possible.
Maybe for some kind of performance reasons?

# Proposed solution

It would be very simple to add more sorting possibilities.
I added `file.created` and `file.changed` column sorting options, and it works:

```diff
  ->enableSorting(
      [
          ['column' => 'fileVersionMeta.title', 'title' => 'sulu_admin.title'],
+         ['column' => 'file.created', 'title' => 'sulu_admin.created'],
+         ['column' => 'file.changed', 'title' => 'sulu_admin.changed'],
      ],
  )
```

But as I said upper, maybe this isn't done currently for some reasons.

**Comment by alexander-schranz** [comment]
Is this a common usecase you have?

I personally currently already not happy with the `changed`, `created`, `published` in the page. Because it is a date a content manager can not edit themselve. I personally if I could revert it only have for pages the `authored` date and nothing else as that the date which can be edit by content manager. But I understand that from business application part something like `changed` or `created` can be interesting.

For the performance I think the `media.created` and `media.changed` would best fit here as they has already an index on it, which the file dont have: https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Media.orm.xml#L10

/cc @chirimoya what do you think about adding this?

**Comment by chirimoya** [comment]
@alexander-schranz I'm fine with adding `created` and `changed` to be more consistent with other providers.

**Comment by Jupi007** [comment]
> Is this a common usecase you have?

Yes, I'd like to create a kind of gallery with the most recent images on top.
And it is imo a common feature.

**Comment by Jupi007** [comment]
As you approve to add this, I'll create a PR.
