### ISSUE TITLE
Feature request: Allow fragments (and query string) for media-links

### ISSUE THREAD

**Issue by spackmat** [sulu/sulu#7082]
# Problem description

At the moment (Sulu 2.5) links to files from the media management cannot have an additional query string nor fragments. My usecase is a big PDF file with legal information, where we linked to certain pages by adding a `#page=72` fragment to our links in the past. Now with Sulu that is only possible by linking this PDF as external resource with an absolute URL (due to #5875), which is a hacky workaround.

# Proposed solution

I would prefer an input for additional query string and fragments for the created URL of the selected media element. As there may be already a query string in place, that field could take inputs like `query=whatever&anotherquery=anyhow#page=72` or `#page=72` and decide on its own, if it renders the content with `?` or `&`. That would be the most flexible solution in my opinion.

And having #6718 in mind, that would also allow setting `inline=1` manually instead of having an extra select for that.

What do others think?

**Comment by alexander-schranz** [comment]
If I understand you correctly you are missing the `#fragments` fields inside the `Text Editor` / `CKeditor` links? Because outside of it via single_media_selection I would go this way via 2 fields:

```xml
<property name="document" type="single_media_selection" colspan="9">
    <meta>
        <title lang="en">Document</title>
    </meta>
</property>

<property name="documentPage" type="number">
    <meta>
        <title lang="en">Page</title>
        <info_text lang="en">Optional page of a selected PDF</info_text>
    </meta>

    <params>
        <param name="step" value="1"/>
        <param name="multiple_of" value="1"/>
    </params>
</property>
```

```twig
{% set mediaUrl = sulu_get_media_url(content.document, 'inline') %}
{% if content.documentPage %}
     {% set mediaUrl ~= '#' ~ content.documentPage %}
{% endif %}

<a href="{{ mediaUrl }}">Download</a>
```

**Comment by spackmat** [comment]
Hey, thanks for your solution for `single_media_selection` types. That could be helpful in other contexts.

Here I mean both a `link` content-type and the links within the `Text Editor`.

The `link` content-type already has a `enable_anchor` option, but that only applies to internal links, not external links (that do not need it) nor media links. At that point, I just want the other link types have that input field for the anchor. (I call that fragment as the anchor describes the target and not the part of the URI, which I mean here.)

Inside the `Text Editor` a link to media also just has inputs for the file, a link-target-attribute and an alt-text in that case, which the `link` content-type does not have.

In both cases, it would be great to have that "anchor" field from the internal link type.

**Comment by spackmat** [comment]
Btw. the fact, that I cannot link to media with `inline=1` from a media link within a text editor, is even more cumbersome than the missing fragments. So now, all our linked PDF files are downloaded instead of being shown in the browser. That raises the question for me: Why are those already existing fields disabled on purpose for media links in the first place? The inline-query-parameter is a core functionality of Sulu and fragments are also valid parts of an URI of media resources.

**Comment by alexander-schranz** [comment]
@spackmat you can make `inline=1` the default for your installation see the documentation about inline links here: https://docs.sulu.io/en/2.5/reference/twig-extensions/functions/sulu_get_media_url.html. There is no purpose behind it I think just nobody yet had the usecase yet to modify media urls or link inside pdfs, even I was not aware that fragments exists inside pdf links.

**Comment by spackmat** [comment]
That helps, indeed. Thanks.

Would a PR to enable fragments and query strings for media links be appreciated?

**Comment by spackmat** [comment]
Hey, I bump that topic as that problem arises again for us. If I provide a PR enabling the anchor field for internal media links, would that stand a chance to be accepted?

**Comment by spackmat** [comment]
We have some (quite large) PDF files with regulatory content and thus an official published state (as in we cannot change the requirements) where we heavily (as in hundreds of links) rely on that `#page=x` URL fragment. At the moment we link to those files via the external link type, but that is a cumbersome workaround as it also works around the whole media system of Sulu. So you could make us very happy, if my little PR could be accepted.

**Comment by spackmat** [comment]
Hey, nevermind. I close my issue now as won't fix, as I don't see any reaction for months and I won't contribute again. We deprecated Sulu for our project anyway for several reasons. One of it is that even such snack-sized contributions like this one (and its PR) are simply ignored for months and I only want to invest resources for contributions for a system where I feel welcomed and not ignored. (And that feature is important for us and having it not accepted has been a showstopper for too long now for that certain project.)

**Comment by alexander-schranz** [comment]
Hello @spackmat,

Sorry to hear that, we sure did got with the timeline of the 2.6 release behind our planned schedule. Specially we wanted to not release 2.6 without some of the most requested features like  [media reference](https://github.com/sulu/sulu/issues/6507) and [single sign on](https://github.com/sulu/sulu/issues/6514). And so it happens that merge requests because leak of review resources from our side get scheduled behind others, to avoid such things beside recurring calls with our [partners](https://sulu.io/partner/find-a-partner) we did begin end of last year have also with our most active community members a recurring call to bring up also external issues and merge requests again on our list and also get there direct feedback. Sometimes tools like our [Slack channel](https://sulu.io/services/support#chat) are also a better way to get directly connection to us than over Github. We sure never will be mad if somebody pings us about something again. At currently state we are in the release cycle of 2.6 and will have a look at all open merge requests when the main issues are resolved. This also includes other community merge requests like the [icon selection](https://github.com/sulu/sulu/pull/6872). Still we lost you as a community members I want to thank you for your feedback, contributions but specially also your transparency in this situation why you not longer wanted to choice Sulu. Wish you the best and maybe we can in future again get your trust back. We also will bring this topic up in our next contributors meeting to avoid such situations like this and get a learning out of it.

Thank you and Best Regards,
Alex
