### ISSUE TITLE
There is no Metadata available for the type 'form' with the key 'contact_details'

### ISSUE THREAD

**Issue by HajjajiGhada** [sulu/sulu#7189]
Hello everyone,

I've been working on the Sulu contact section, adding a new social media feature. Everything was working perfectly in the local environment, but when I deployed the project, I encountered a 404 error with the message: "There is no Metadata available for the type 'form' with the key 'contact_details' in /var/www/html/sources/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataProvider.php on line 88."

I need your help to resolve this issue. If you have any ideas or solutions, please share them.

**Comment by alexander-schranz** [comment]
As written in Slack this issue is resolved. For all stumbling over similar issues make sure to run:

```
rm -rf var/cache
```

and check if the containers are build without any issues:

```
bin/console cache:clear
# and
bin/websiteconsole cache:clear
```

If you are seeing the messages on the Symfony Profiler error page also have a look at the previous Exception Messages as it could be also caused by another issue with the metadata.

**Comment by fnagel** [comment]
Note: make sure not to have any (invalid or unwanted?) other xml files in the configs. I tried to use an include within the form xml files of my custom records. I had the include file in `config/forms/fragments/meta.xml` which will cause the issue. Using `config/includes/forms/meta.xml` works just fine.

My error message was `There is no Metadata available for the type "form" with the key "profile_details".`
