### ISSUE TITLE
Compatibility with Symfony 6.4

### ISSUE THREAD

**Issue by NicoHaase** [sulu/sulu#7240]
| Q | A
| --- | ---
| Sulu Version | 2.5.11
| PHP Version | 8.1.26
| DB Version | -
| Browser Version | -

# Actual Behavior

Sulu cannot be used with Symfony 6.4 currently

# Expected Behavior

An update to Symfony 6.4 is possible

# Explanation

- `sulu/sulu` depends on `doctrine/persistence` v2
- `sulu/sulu` also depends on `doctrine/doctrine-bundle`, which depends on `symfony/doctrine-bridge`
- `symfony/doctrine-bridge` in v6.4 depends on `doctrine/persistence` v3 (see https://github.com/symfony/symfony/issues/52834)

# Possible Solutions

Check whether Sulu can also work with `doctrine/persistence` v3

**Comment by NicoHaase** [comment]
@alexander-schranz if you think this change might be possible, I could try to work on it

**Comment by alexander-schranz** [comment]
@NicoHaase Thx for the report the persistence update is currently in progress here: https://github.com/sulu/sulu/pull/7235. After that is fixed it should not longer block the persistence / doctrine bridge update.

**Comment by dduenker** [comment]
Symfony 6.3 is now EOL.

**Comment by fnagel** [comment]
Will it be possible to Sulu 2.5.11 (for Symfony 6.4) without using doctrin/orm v3? Because using doctrine v3 will take some time due to dependencies to other packages.

**Comment by alexander-schranz** [comment]
There is not yet support for doctrine/orm 3 in Sulu, that is a seeprate task. Symfony 6.4 can currently used for 99% of the symfony packages the only one which is not compatible is `symfony/doctrine-bridge` which need currently be on 6.3 for Sulu 2.5, as `symfony/doctrine-bridge:6.4` requires `doctrine/persistence: 2.0` which is only compatible with `Sulu 2.6` because of minimal bc breaks on the list query builders as it is not longer able to use `<bundle>:<entityName>`. 

Currently you can upgrade to 6.4 by change your `composer.json` in your 2.5 installation to:

```json
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "6.3.* || 6.4.*"
        }
    }
```

And run `composer update`. You will get then the symfony 6.4 packages the only one currently blocked is the doctrine-bridge because of the persistence bundle. But you can then already use all Symfony 6.4 features.

**Comment by fnagel** [comment]
@alexander-schranz Thanks (again) for the fast help! With your snippet, the update worked with a small issue regarding the admin JS build. Please see here: #7274

**Comment by mamazu** [comment]
This can be closed. Sulu works with Symfony 6.4.
