### ISSUE TITLE
CKEditor + plugin source editing HTML is replaced

### ISSUE THREAD

**Issue by paweelkopec** [sulu/sulu#7251]
| Q | A
| --- | ---
| Sulu Version |  2.5.0
| PHP Version | 8.2.14  
| DB Version |  MySQL  8.0.19
| Browser Version | Chrome 

# Actual Behavior

When editing the source code, adds code as follow:

`<div class="row">test </div>`

This code abowe is replaced to:
`<p> test</p>`
# Expected Behavior

The HTML code isn't changed:

`<div class="row">test </div>`

# Steps to Reproduce

assets/admin/package.json
add devDependencies

"@ckeditor/ckeditor5-font": "^34.2.0",
"@ckeditor/ckeditor5-source-editing": "^34.2.0"
        
admin/assets/admin/app.js
       
`import {ckeditorPluginRegistry, ckeditorConfigRegistry} from 'sulu-admin-bundle/containers';
import Font from '@ckeditor/ckeditor5-font/src/font';
import { SourceEditing } from '@ckeditor/ckeditor5-source-editing';
ckeditorPluginRegistry.add(Font);
ckeditorPluginRegistry.add(SourceEditing);
ckeditorConfigRegistry.add((config) => ({
    toolbar: [...config.toolbar, 'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor','sourceEditing'],
}));`

npm install
npm run build

**Comment by alexander-schranz** [comment]
I think that is the expected behaviour of CKEditor. CKEditor is converting all kind of things which it does not have a plugin for to one which it knows. So If you write `<div class="row">test </div>` It is something which CKEditor does not know and convert to `<p>Test</p>` which is part of the ParagraphPlugin. All tags which it even can not convert it even removes.

So the Source Code Editing Plugin does just allow you to edit the source code directly. Not add new features / tags to it what CKEditor does not have a related Plugin installed.

In newer version of CKEditor there are Plugins for more HTML tags. But at the current used CKEditor version you would require to create you own Plugin which handles the `div.row` class.
