### ISSUE TITLE
Route won't persist in ro_routes when creating entity

### ISSUE THREAD

**Issue by manuxi** [sulu/sulu#7591]
| Q | A
| --- | ---
| Sulu Version | 2.6.4
| PHP Version | 8.3.3
| DB Version | MySQL 5.7.32
| Browser Version | Chrome 128.0.6613.138

# Actual Behavior

I have discovered a problem with the new Sulu version 2.6.4 that I did not met before in Sulu 2.5.x.
In different bundles I'm an entity in each case with a route_path property. This should be persisted in ro_routes after creation when calling RouteManager::createOrUpdateByAttributes(). But it won't persist.

When editing the entity and store it, the route is persisted in ro_routes.

# Expected Behavior

Route of the entity is persisted on creation in ro_routes.

# Steps to Reproduce

In my controller, I have the following function that creates my entity:

```
#[Route('/archive', name: 'post_archive', methods: 'POST')]
public function postAction(Request $request): Response
{
    $entity = $this->archiveModel->createArchive($request);
    $this->updateRoutesForEntity($entity);
    [...]
}
```
The updateRoutesForEntity method looks like this:
```
protected function updateRoutesForEntity(Archive $entity): void
{
    $this->routeManager->createOrUpdateByAttributes(
        Archive::class,
        (string) $entity->getId(),
        $entity->getLocale(),
        $entity->getRoutePath()
    );
}
```

After creation of an object no entry is created in the ro_routes table.

# Possible Solutions

Digging through RouteManager::createOrUpdateByAttributes() the last action beeing taken is $this->routeRepository->persist($route) which in turn calls EntityManager()->persist($route).
No EntityManager()->flush() is called.

When I add in my tests RouteRepository::flush() (which calls EntityManager::flush()) and add $this->routeRepository->flush() to RouteManager::createOrUpdateByAttributes() the route is stored to ro_routes as it should on creation.

**Comment by alexander-schranz** [comment]
That is the expected behaviour you need to run `EntityManager::flush` yourself. This is specially what you want todo if you example create multiple items inside the same process you normally don't want to overhead of flush after every item. So calling flush is in your hands  at the time you want to flush the changes, we will not auto flush your changes in this manager.

Even we will remove all flushes from all managers at some times as flushes should only be done inside controllers / commands which knows if there are multiple or only one creation dones and not inside services.

**Comment by manuxi** [comment]
Didn't know that, thank you for clearing that up!
