### ISSUE TITLE
Define an image format with max-width and max-height, keeping source ratio?

### ISSUE THREAD

**Issue by etiennerunge** [sulu/sulu#7645]
| Q | A
| --- | ---
| Sulu Version | 2.6.5
| PHP Version | 8.2
| DB Version | mysql  8.4.0
| Browser Version | Firefox 132.0 64bits

# Actual Behavior

When defining image format with inset mode, it keeps ratio if you crop manually the image.

And yet, if you doesn't crop your image, it resizes correctly the image. 

# Expected Behavior

User may be free to crop its image inside max width and max height values, independently from ratio

# Steps to Reproduce

With this image format

```
    <!-- Max width and max height -->
    <format key="1080x1080-inset">
        <scale x="1080" y="1080" mode="inset"/>
    </format>
```

1 - add image with bigger dimension. 
2 - Display image from format 1080x1080-inset: `{{ media.thumbnails['1080x1080-inset'] }}` 

![image](https://github.com/user-attachments/assets/16c0079f-0df4-46c1-8bcb-347850134a97)
(it's ok,  image width is 1080px width)
 
3 - try to crop image

![image](https://github.com/user-attachments/assets/474a0576-1560-4d20-a706-9f7775df0cdf)

4 - It's not ok because of square format ratio 

![image](https://github.com/user-attachments/assets/cb3a77df-02fa-449d-b214-f87531829ad1)

# Possible Solutions

Could format image defines x and y values independently ? Is there a way to avoid keeping ratio of image format (but keeping source image ratio, fixing boundaries) ?

PS: It seems that   `mode="outbound" ` is undocumented. Does this option could help me ? 
Sorry wrong label, it should be _feature_

**Comment by alexander-schranz** [comment]
The `outbound` is the default so it not requires special documentation. The mode only effects when height and width is given:

All possibilites currently are documented in https://docs.sulu.io/en/2.6/book/image-formats.html.

 - fixed width, dynamic height
 - dynamic height, fixed width
 - fixed width, fixed height
 - max width, max height
 
I don't see why we should add an option for keep the source ratio. If somebody want to crop it that way why avoid that if you defined only max width and max height definitions, as they could also just upload a squared image and it is then used. If you want a specific ration you should force it, but if your are on max width and height they should be able to crop it they way they want it in my opinion.

The only thing I could think of to support "shift" key like in other image edit application and aslong as used it keeps the ratio while cropping. But in my opinion an option to force from source ratio, is contra productive as they would be unncessary forced for reupload a new version instead of crop exist image.

**Comment by etiennerunge** [comment]
Thanks a lot for your reply.

I understand your point of view and it helps me to understand this feature better.

I think, after reading your response, my problem could be solving in another way.
At the beginning of my problem is the customer. He uploads a lot of images, without paying attention of formats and weights: 9000px wide, 15MB etc... I have to create kind of fullscreen gallery of images, with landscape and portrait images. 

So I defined 1080x1080-inset image format, to restrict weight and width/height of all images. But Customer doesn't understand how it works and try to resize them in app with cropping feature, but it generates square images.

I think the solution is that the customer doesn't have to crop image, but should just modify focus point (or editing images before uploading them in sulu)

What do you think about that ? Maybe miss I something.

**Comment by alexander-schranz** [comment]
The `inset` images needs lot of attention on the implementation side, I'm not sure why your customer tried to crop them when they wanted to see the full image?

Did you accidently crop the image on the website with CSS? That something you definitely should avoid as it make things untransparent for the content manager, what is cropped by the image format and what is cropped by CSS. CSS cropping so should be avoided in any case and things like `background cover` and `object-fit: cover;` avoided were possible to make things transparent for the content manager. For cropped images use cropped image formats.

So if you have a inset image you should make sure that they see the full image and it don't get cropped away.

For showing images fullscreen I think that your choice of inset image format totally make sense. I mostly go the rule if you have a image gallery on your website. You can define the gallery thumbnails itself with fixed width and fixed height, aslong no masonry view is used. But opening the image should show the whole image so best a `inset` format. So in most cases you have 2 different image formats for a image gallery one for the thumbnails one for the fullscreen overlay. So maybe you did reuse the same format on preview and the fullscreen? That may something which did confuse the content manager instead of having seperate image formats?

And yeah mostly the focus point is a good way for the content manager instead of cropping that should if possible be prefereed as it is attended to all image formats. But for inset image focus point has no effects as not being cropped.

PS: Sometimes naming the image formats helps  for better transparents. I tried something like this (1940x1080-inset Gallery Fullscreen, 200x100 Gallery Preview, ...)

**Comment by etiennerunge** [comment]
Thanks for your reply :)

No I don't crop image with css, I try to have clean and minimal images weight, accurate sizes. 

I think using inset mode with image format 1080x1080 do the trick, it allows automatic image resizing for both format: landscape and portrait, keeping image ratio. I use sulu 300x300 for thumbnails, format that can't be manually set by user, but, if I understand, resize and crop automatically image according to focus point ? 

But if content manager accidentally set 1080x1080 format on one image, this image in the gallery will be square. Is there a way to delete this change on one image? Or can we register 1080x1080-inset format without showing this format to content manager? 

Best regards

**Comment by alexander-schranz** [comment]
Image crops in sulu are per image format as you see in the cropping feature the image format dropdown if no crop is defined by the content manager the crop mechanism will fallback to the focus point and do its best to crop by that which is define once for all image formats.

If you want to remove all crops for specific format you can remove them from the database table but you need to increase also the subversion of your fileVersion so browsers get a new query string and request the image again else the old image is still cached in there browser.

**Comment by etiennerunge** [comment]
Thanks @alexander-schranz for your patience and your help. I keep 1080x1080-inset format and discourage content manager to use crop tool. It think it could be usefull to give user chance to delete cropped image, to fallback to default behavior.

Solution is found, this issue is not relative to bug or feature anymore, so I close it. 
Thanks again for your help :) long life to sulu I definitly like it :heart:
