### ISSUE TITLE
Implement "soft delete" for users/contacts

### ISSUE THREAD

**Issue by christianbader** [sulu/sulu#921]
Since some data (e.g. products) depending on existing users, deleting a user may cause serious results.
Thus, a user should only be "soft deletable".

For implementation details see:
https://github.com/l3pp4rd/DoctrineExtensions/blob/master/doc/softdeleteable.md

**Comment by wachterjohannes** [comment]
i have tried to implement the gedmo doctrine extension for softdelete it works very well and performance is good! Normal stuff works very well and is fast implemented, activated and could be used as is.

But there are at least one "bigger" problem i found: When you get a proxy for a deleted object from doctrine you get an exception if you call a method on that object. because doctrine cannot find a entity with the id (because of the where statement added by gedmo). we have to take a look deeper into it, or take care of loading creator and changer always (without lazy) then you get null and you can check it.

**Comment by wachterjohannes** [comment]
i have fount no issue which fits perfectly in gedmo but maybe this also is related https://github.com/Atlantic18/DoctrineExtensions/issues/1463

**Comment by wachterjohannes** [comment]
i will remove the milestone because we have to take a deeper look into it!

**Comment by danrot** [comment]
Since we have never dug deeper, and continued to fix issues where missing users were causing problems, I am going to close this issue. Users can still be locked, and I guess because of GDPR it should still be possible to really delete them.
